// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authentication status for broker connections.
 *
 * Note: Additional variants (Valid, ExpiringSoon, Expired) will be added
 * when auth status monitoring is implemented.
 */
export type AuthStatus = { "status": "not_configured" };
