// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authentication status for broker connections.
 */
export type AuthStatus = { "status": "not_configured" };
