// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Circuit breaker status for the trading system.
 */
export type CircuitBreakerStatus = { "status": "active" };
