// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventStoreEntry = { aggregate_type: string, aggregate_id: string, sequence: number, event_type: string, timestamp: string, };
