// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolInventory } from "./SymbolInventory";
import type { UsdcInventory } from "./UsdcInventory";

export type Inventory = { perSymbol: Array<SymbolInventory>, usdc: UsdcInventory, };
