// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeframeMetrics } from "./TimeframeMetrics";

export type PerformanceMetrics = { "1h": TimeframeMetrics, "1d": TimeframeMetrics, "1w": TimeframeMetrics, "1m": TimeframeMetrics, all: TimeframeMetrics, };
