// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Position information for a symbol.
 */
export type Position = { symbol: string, net: string, };
