// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Placeholder for rebalance operation tracking.
 */
export type RebalanceOperation = { id: string, };
