// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventStoreEntry } from "./EventStoreEntry";
import type { InitialState } from "./InitialState";

/**
 * Messages sent from the server to WebSocket clients.
 *
 * Note: Variants for future message types (trades, positions, metrics, etc.)
 * will be added as their respective dashboard panels are implemented.
 */
export type ServerMessage = { "type": "initial", "data": InitialState } | { "type": "event", "data": EventStoreEntry };
