// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventStoreEntry } from "./EventStoreEntry";
import type { InitialState } from "./InitialState";

/**
 * Messages sent from the server to WebSocket clients.
 */
export type ServerMessage = { "type": "initial", "data": InitialState } | { "type": "event", "data": EventStoreEntry };
