// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitialState } from "./InitialState";
import type { InventorySnapshot } from "./InventorySnapshot";
import type { Statement } from "./Statement";
import type { Trade } from "./Trade";
import type { TransferOperation } from "./TransferOperation";

/**
 * Messages sent from the server to WebSocket clients.
 */
export type ServerMessage = { "type": "initial", "data": InitialState } | { "type": "fill", "data": Trade } | { "type": "snapshot", "data": InventorySnapshot } | { "type": "transfer", "data": TransferOperation } | { "type": "statement", "data": Statement };
