// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpreadSummary = { symbol: string, lastBuyPrice: string, lastSellPrice: string, pythPrice: string, spreadBps: string, updatedAt: string, };
