// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PnL } from "./PnL";

export type TimeframeMetrics = { aum: string, pnl: PnL, volume: string, tradeCount: number, sharpeRatio: string | null, sortinoRatio: string | null, maxDrawdown: string, hedgeLagMs: number | null, uptimePercent?: string, };
