// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Placeholder for trade information.
 *
 * Note: Full type structure will be added when trades panel is implemented.
 */
export type Trade = { id: string, };
