# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{ copyPathToStore, fetchFromGitHub, fetchgit, fetchurl, ... }: {
  "@playwright/test@1.54.1" = fetchurl {
    url = "https://registry.npmjs.org/@playwright/test/-/test-1.54.1.tgz";
    hash =
      "sha512-FS8hQ12acieG2dYSksmLOF7BNxnVf2afRJdCuM1eMSxj6QTSE6G4InGF7oApGgDb65MX7AwMVlIkpru0yZA4Xw==";
  };
  "fsevents@2.3.2" = fetchurl {
    url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
    hash =
      "sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
  };
  "playwright-core@1.54.1" = fetchurl {
    url =
      "https://registry.npmjs.org/playwright-core/-/playwright-core-1.54.1.tgz";
    hash =
      "sha512-Nbjs2zjj0htNhzgiy5wu+3w09YetDx5pkrpI/kZotDlDUaYk0HVA5xrBVPdow4SAUIlhgKcJeJg4GRKW6xHusA==";
  };
  "playwright@1.54.1" = fetchurl {
    url = "https://registry.npmjs.org/playwright/-/playwright-1.54.1.tgz";
    hash =
      "sha512-peWpSwIBmSLi6aW2auvrUtf2DqY16YYcCMO8rTVx486jKmDTJg7UAhyrraP98GB8BoPURZP8+nxO7TSd4cPr5g==";
  };
}
