[evm]
rpc_url = "http://localhost:9999"

[broker]
type = "dry-run"

[hyperdx]
api_key = "e2e-test-key"

[issuance]
base_url = "http://localhost:8000"
api_key = "0xaabbccddeeff00112233445566778899aabbccddeeff00112233445566778899"
