server_port = 8002
log_level = "debug"
database_url = "sqlite:///mnt/data/st0x-experimental.db"
hyperdx.service_name = "st0x-experimental"

[broker.travel_rule]
beneficiary_entity_name = "T0 TRADE (BVI) LTD"

[raindex]
orderbook = "0xe522cB4a5fCb2eb31a52Ff41a4653d85A4fd7C9D"
# what block to backfill from
deployment_block = 43259507
order_owner = "0x386C24644E532387b03C1992cA83542492A3ac32"

[assets.cash]
vault_id = "0xfab"
rebalancing = "disabled"

[assets.equities.RKLB]
trading = "enabled"
rebalancing = "disabled"

vault_id = "0xfab"
tokenized_equity = "0xf6744fd94e27c2f58f6110aa9fdc77a87e41766b"
tokenized_equity_derivative = "0xf4f8c66085910d583c01f3b4e44bf731d4e2c565"
