//! Apalis job that orchestrates wrapped-equity recovery.
//!
//! Enqueued per symbol and chain with a positive wrapped wallet balance
//! (`BaseWalletWrappedEquity` or `ChainWalletWrappedEquity`), naming the
//! chain whose wallet holds it. The job is a thin orchestrator:
//! it reads `InventoryView`, picks a dispatch path, and sends the command
//! sequence through the aggregate's store. All side effects (raindex
//! deposit/confirm, mint/redemption resume, wrapped-token lookup) live in
//! the aggregate's command handlers via its `Services`.
//!
//! Steps:
//!
//! 1. Claim the `equity_in_progress` guard for the symbol (from absent or
//!    `HeldForRecovery` on the job's chain). If a live transfer owns it
//!    (`ActiveTransfer`) or another chain's recovery holds it, the job
//!    reschedules itself with a delay so an unchanged wallet balance is not
//!    stranded waiting for another snapshot.
//! 2. Read the job chain's wallet balance and active mint/redemption from
//!    the inventory view to pick a `DispatchDecision`. A transfer of the
//!    symbol on another chain makes the job reschedule, never dispatch or
//!    take the orphan path.
//! 3. Send `Detect` followed by the path-specific command sequence:
//!    `DispatchToMint`, `DispatchToRedemption`, or `SubmitOrphanDeposit +
//!    ConfirmOrphanDeposit`. The aggregate's terminal state encodes the
//!    outcome; no separate completion command is needed.
//!
//! The job carries its `WrappedEquityRecoveryId` in the apalis payload
//! (generated by the reactor when pushing the job) so retries target the
//! same aggregate -- the next command in the sequence picks up wherever
//! the previous attempt stopped.
//!
//! A job whose chain has no equity services reschedules itself and raises
//! an operational alert instead of failing the recovery: the tokens stay in
//! that chain's wallet until the chain is wired again.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, RwLock};
use std::time::Duration;
use thiserror::Error;
use tracing::{debug, error, info, warn};

use st0x_event_sorcery::{AggregateError, LifecycleError, SendError, Store};
use st0x_evm::Chain;
use st0x_execution::{FractionalShares, Symbol};
use st0x_tokenization::IssuerRequestId;

use super::aggregate::{
    DetectionFailureDisposition, WrappedEquityRecovery, WrappedEquityRecoveryCommand,
    WrappedEquityRecoveryError, WrappedEquityRecoveryId,
};
#[cfg(test)]
use crate::bot_gas::BotGasReceiptCostEnqueuer;
use crate::bot_gas::redrive::{BotGasFailureClassifier, redrive_on_bot_gas_failure};
use crate::conductor::job::{BackpressureStreak, Job, JobQueue, Label, QueuePushError};
use crate::equity_redemption::{EquityRedemption, RedemptionAggregateId};
use crate::inventory::BroadcastingInventory;
use crate::inventory::view::{InFlightEquityLocation, InventoryView};
use crate::rebalancing::trigger::{GuardState, RecoveryGuard, claim_guard_for_recovery_or_orphan};
use crate::tokenized_equity_mint::TokenizedEquityMint;

/// Apalis queue type for [`WrappedEquityRecoveryJob`].
pub(crate) type WrappedEquityRecoveryJobQueue = JobQueue<WrappedEquityRecoveryJob>;

/// Dependencies the recovery job needs to claim the per-symbol concurrency
/// guard, read inventory, and send commands through the aggregate's store.
/// Services (raindex/wrapper/transfer) live on the store -- not here.
pub(crate) struct WrappedEquityRecoveryCtx {
    pub(crate) inventory: Arc<BroadcastingInventory>,
    pub(crate) store: Arc<Store<WrappedEquityRecovery>>,
    pub(crate) mint_store: Arc<Store<TokenizedEquityMint>>,
    pub(crate) redemption_store: Arc<Store<EquityRedemption>>,
    pub(crate) equity_in_progress: Arc<RwLock<HashMap<Symbol, GuardState>>>,
    /// Queue used for delayed self-reschedule when the shared equity guard is
    /// held by another recovery/transfer job.
    pub(crate) queue: WrappedEquityRecoveryJobQueue,
    pub(crate) reschedule_interval: Duration,
}

/// Why a single recovery job attempt failed. Errors propagate up through
/// apalis; most service-call failures inside the aggregate's command
/// handlers are recorded as `RecoveryFailed` events and don't surface here.
/// The one exception is a bot-gas enqueue failure
/// (`WrappedEquityRecoveryError::BotGasEnqueueFailed`), which the aggregate
/// deliberately propagates so it reaches `finish`'s
/// `redrive_on_bot_gas_failure` call instead of permanently failing the
/// recovery over a best-effort accounting write.
#[derive(Debug, Error)]
pub(crate) enum WrappedEquityRecoveryJobError {
    #[error("recovery aggregate error: {0}")]
    Aggregate(#[from] SendError<WrappedEquityRecovery>),
    #[error(transparent)]
    Domain(#[from] WrappedEquityRecoveryError),
    #[error(
        "inventory view reports both an active mint ({mint_id}) and active redemption \
         ({redemption_id}) for symbol {symbol} -- aborting recovery"
    )]
    ConflictingActiveTransfers {
        symbol: Symbol,
        mint_id: IssuerRequestId,
        redemption_id: RedemptionAggregateId,
    },
    #[error(
        "active mint {mint_id} for symbol {symbol} carries quantity {aggregate_shares}, \
         which does not match the wrapped-equity wallet snapshot {snapshot_shares} -- \
         refusing to dispatch to a stale aggregate"
    )]
    ActiveMintQuantityMismatch {
        symbol: Symbol,
        mint_id: IssuerRequestId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },
    #[error(
        "active redemption {redemption_id} for symbol {symbol} carries quantity \
         {aggregate_shares}, which does not match the wrapped-equity wallet snapshot \
         {snapshot_shares} -- refusing to dispatch to a stale aggregate"
    )]
    ActiveRedemptionQuantityMismatch {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },
    #[error(
        "{symbol} has an active {transfer} on {transfer_chain}, but this recovery runs on \
         {recovery_chain} -- waiting for that transfer instead of dispatching across chains"
    )]
    ActiveTransferOnOtherChain {
        symbol: Symbol,
        transfer: String,
        transfer_chain: Chain,
        recovery_chain: Chain,
    },
    #[error("active mint {mint_id} for symbol {symbol} is missing from the mint store")]
    ActiveMintMissing {
        symbol: Symbol,
        mint_id: IssuerRequestId,
    },
    #[error(
        "active redemption {redemption_id} for symbol {symbol} is missing from the \
         redemption store"
    )]
    ActiveRedemptionMissing {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
    },
    #[error("active mint store error: {0}")]
    ActiveMintAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::tokenized_equity_mint::TokenizedEquityMint>,
        >,
    ),
    #[error("active redemption store error: {0}")]
    ActiveRedemptionAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::equity_redemption::EquityRedemption>,
        >,
    ),
    #[error("failed to reschedule recovery job after guard contention: {0}")]
    Reschedule(#[from] QueuePushError),
}

/// Apalis job payload. The reactor pushes one of these per symbol and chain
/// with a positive wrapped wallet balance, generating a fresh
/// `recovery_id` at push time so apalis retries hit the same aggregate.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub(crate) struct WrappedEquityRecoveryJob {
    /// The chain whose wallet holds the shares. Rows queued before jobs
    /// named their chain ran on Base.
    #[serde(default = "crate::onchain::legacy_chain")]
    pub(crate) chain: Chain,
    pub(crate) symbol: Symbol,
    pub(crate) recovery_id: WrappedEquityRecoveryId,
    /// Count of consecutive broker rate-limit (429) reschedules leading up to
    /// this attempt (RAI-1494). `#[serde(default)]` so a row enqueued under
    /// the pre-this-change payload shape still deserializes to `0` instead of
    /// crashing the poll stream's `sqlx::Decode`.
    ///
    /// NOT YET wired to a reschedule: `resume_mint`/`resume_redemption`
    /// failures are caught inside the aggregate's command handler and
    /// recorded as a terminal `RecoveryFailed` event with only a
    /// Display-formatted `String` reason (see `resume_mint_or_fail` /
    /// `resume_redemption_or_fail` in `aggregate.rs`) -- `ctx.store.send()`
    /// therefore returns `Ok(())` regardless, so `perform()` never observes
    /// an `Err` to classify for this failure class, and `find_backpressure`
    /// cannot walk to a real Alpaca error type from any constructible
    /// `WrappedEquityRecoveryJobError` today. This is pre-existing behavior,
    /// not a regression: a 429 here has always immediately terminalized the
    /// recovery with zero retries. Closing this gap needs the aggregate's
    /// error type to preserve the classified error (not just its Display
    /// string) and `transition()` to return `Err` instead of
    /// `Ok(RecoveryFailed)` on a classified 429, plus threading this streak
    /// into the `Command` (the aggregate has no visibility into the job's own
    /// payload) -- a redesign of the aggregate's error contract, out of scope
    /// for this task's per-job wiring. Field added now so the payload schema
    /// is ready when that follow-up lands.
    #[serde(default)]
    pub(crate) backpressure_streak: BackpressureStreak,
}

impl Job<WrappedEquityRecoveryCtx> for WrappedEquityRecoveryJob {
    type Output = ();
    type Error = WrappedEquityRecoveryJobError;

    const WORKER_NAME: &'static str = "wrapped-equity-recovery-worker";

    const PERFORM_TIMEOUT: Option<std::time::Duration> =
        Some(crate::conductor::job::DEFAULT_PERFORM_TIMEOUT);

    #[cfg(any(test, feature = "test-support"))]
    const JOB_KIND: crate::conductor::job::JobKind =
        crate::conductor::job::JobKind::WrappedEquityRecovery;

    fn label(&self) -> Label {
        Label::new(format!(
            "WrappedEquityRecovery:{}:{}:{}",
            self.chain, self.symbol, self.recovery_id
        ))
    }

    async fn perform(&self, ctx: &WrappedEquityRecoveryCtx) -> Result<Self::Output, Self::Error> {
        let symbol = self.symbol.clone();

        let current_state = ctx.store.load(&self.recovery_id).await?;
        if let Some(state) = &current_state
            && state.chain() != self.chain
        {
            if !state.is_terminal() {
                fail_on_chain_mismatch(ctx, self, state.chain()).await?;
            }
            return Ok(());
        }

        // Two-path claim: this job handles a positive wrapped wallet
        // balance, which can be either an orphan (absent guard) or the
        // landed-but-unconfirmed `WrapSubmitted` outcome -- the wrap tx
        // actually landed so the tokens are WRAPPED, but the confirmation read
        // failed and the transfer job handed the slot to recovery as
        // `HeldForRecovery`. Claiming `HeldForRecovery` here is what drains that
        // slot; refusing it (as the old orphan-only claim did) left it wedged
        // because `UnwrappedEquityRecovery` `NoBalanceSkip`s on a wrapped
        // balance. The atomic claim makes a concurrent `UnwrappedEquityRecovery`
        // claim safe -- only one wins, the other reschedules. Returns None only
        // for `ActiveTransfer` (a live transfer job owns the slot) or a
        // `HeldForRecovery` of another chain.
        let Some(guard) =
            claim_guard_for_recovery_or_orphan(&ctx.equity_in_progress, &symbol, self.chain)
        else {
            debug!(
                target: "rebalance",
                chain = %self.chain,
                %symbol,
                recovery_id = %self.recovery_id,
                "Rescheduling wrapped equity recovery: equity_in_progress held by \
                 active transfer or another chain's recovery; deferring",
            );
            ctx.queue
                .clone()
                .push_with_delay(self.clone(), ctx.reschedule_interval)
                .await?;
            return Ok(());
        };

        let mut detected_shares = None;
        if let Some(agg) = ctx.store.load(&self.recovery_id).await? {
            if let WrappedEquityRecovery::Failed {
                detection_failure: Some(disposition),
                ..
            } = &agg
            {
                match disposition {
                    DetectionFailureDisposition::RestartDetection => {
                        self.enqueue_fresh_recovery(ctx).await?;
                    }
                    DetectionFailureDisposition::PreserveHold => {}
                }
                return Ok(());
            }
            if agg.is_terminal() {
                debug!(
                    target: "rebalance",
                    %symbol,
                    recovery_id = %self.recovery_id,
                    "Skipping wrapped equity recovery: aggregate already terminal",
                );
                guard.release();
                return Ok(());
            }

            // Resume dispatch on the current non-terminal state. Enumerated
            // explicitly (no `_` arm) -- mirroring `UnwrappedEquityRecoveryJob`
            // -- so a new non-terminal `WrappedEquityRecovery` state fails to
            // compile here until it is deliberately wired into a resume path,
            // instead of silently falling through to the no-op below.
            match agg {
                // Resume point for a redrive after this attempt's
                // ConfirmOrphanDeposit failed only to enqueue its bot-gas cost
                // (see `is_bot_gas_enqueue_failure` below): the deposit is
                // already confirmed on-chain, so the redriven attempt must
                // re-send ConfirmOrphanDeposit directly, NOT `Detect` --
                // resending `Detect` on an already-initialized aggregate is
                // rejected with `AlreadyInitialized`.
                WrappedEquityRecovery::OrphanDepositSubmitted { .. } => {
                    let result = ctx
                        .store
                        .send(
                            &self.recovery_id,
                            WrappedEquityRecoveryCommand::ConfirmOrphanDeposit,
                        )
                        .await
                        .map_err(Into::into);
                    return finish(ctx, self, guard, result).await;
                }
                // `Detected` has no persisted dispatch decision yet: a job
                // retried after `Detect` succeeded re-derives the
                // mint/redemption/orphan path from `InventoryView` below and
                // skips `Detect`, which an initialized aggregate refuses.
                WrappedEquityRecovery::Detected { shares, .. } => detected_shares = Some(shares),
                // `DispatchedToMint`/`DispatchedToRedemption`/`OrphanDeposited`/
                // `Failed` are already short-circuited by the `is_terminal`
                // early return above; enumerated here (rather than folded into
                // `_`) so this match stays exhaustive and a new non-terminal
                // state fails to compile until it is deliberately wired into a
                // resume arm above.
                WrappedEquityRecovery::DispatchedToMint { .. }
                | WrappedEquityRecovery::DispatchedToRedemption { .. }
                | WrappedEquityRecovery::OrphanDeposited { .. }
                | WrappedEquityRecovery::Failed { .. } => {}
            }
        }

        let Some(snapshot) = read_recovery_snapshot(&ctx.inventory, self.chain, &symbol).await
        else {
            // No wrapped balance to drain this cycle. Do NOT release the guard:
            // an orphan claim drops to absent (the reactor re-triggers on the
            // next positive-balance poll), while a `HeldForRecovery` claim drops
            // back to `HeldForRecovery`. The reactor only re-dispatches on a
            // POSITIVE balance, so a `HeldForRecovery`-origin claim that finds
            // zero balance must self-reschedule or the slot wedges with no job
            // left to drain it.
            if detected_shares.is_some() && !guard.claimed_from_held_for_recovery() {
                // The detected balance is gone, so this recovery can never
                // dispatch; fail it so it does not stay open forever. A
                // later positive balance opens a new recovery.
                warn!(
                    target: "rebalance",
                    %symbol,
                    recovery_id = %self.recovery_id,
                    "Failing detected wrapped equity recovery: wrapped balance is gone",
                );
                ctx.store
                    .send(
                        &self.recovery_id,
                        WrappedEquityRecoveryCommand::FailRecovery {
                            reason: "wrapped balance gone before dispatch".to_owned(),
                        },
                    )
                    .await?;
                guard.release();
            } else if guard.claimed_from_held_for_recovery() {
                debug!(
                    target: "rebalance",
                    %symbol,
                    recovery_id = %self.recovery_id,
                    "Rescheduling wrapped equity recovery: no positive balance yet but slot \
                     is HeldForRecovery; re-enqueueing with delay to keep polling until the \
                     balance resolves or the slot is cleared",
                );
                ctx.queue
                    .clone()
                    .push_with_delay(self.clone(), ctx.reschedule_interval)
                    .await?;
            } else {
                debug!(
                    target: "rebalance",
                    %symbol,
                    recovery_id = %self.recovery_id,
                    "Skipping wrapped equity recovery: no positive balance in inventory view; \
                     orphan claim, guard drop removes entry so future inventory polls can \
                     re-trigger recovery",
                );
            }
            return Ok(());
        };

        // A resumed `Detected` record deposits the shares it stored, so a
        // changed balance makes it stale: fail it and queue a fresh recovery
        // for the current balance, even when polling suppresses unchanged reads.
        if let Some(detected) = detected_shares
            && snapshot.shares != detected
        {
            return self
                .fail_stale_detected(
                    ctx,
                    format!(
                        "wrapped balance changed since detection: detected {detected}, \
                         current {}",
                        snapshot.shares
                    ),
                )
                .await;
        }

        if let Err(error) =
            validate_active_aggregate_quantity(ctx, self.chain, &symbol, &snapshot).await
        {
            if detected_shares.is_some() && error.is_business_validation() {
                return self.fail_invalid_detection(ctx, &error).await;
            }
            return wait_or_retry_after_validation(ctx, self, error).await;
        }

        if detected_shares.is_none() {
            let detected = ctx
                .store
                .send(
                    &self.recovery_id,
                    WrappedEquityRecoveryCommand::Detect {
                        chain: self.chain,
                        symbol: symbol.clone(),
                        shares: snapshot.shares,
                    },
                )
                .await;
            if let Err(error) = detected {
                return finish(ctx, self, guard, Err(error.into())).await;
            }
        }

        info!(
            target: "rebalance",
            %symbol,
            recovery_id = %self.recovery_id,
            shares = %snapshot.shares,
            ?snapshot.dispatch,
            "Wrapped equity recovery: dispatched detection",
        );

        self.dispatch(ctx, guard, snapshot).await
    }
}

impl WrappedEquityRecoveryJob {
    async fn fail_invalid_detection(
        &self,
        ctx: &WrappedEquityRecoveryCtx,
        error: &WrappedEquityRecoveryJobError,
    ) -> Result<(), WrappedEquityRecoveryJobError> {
        error!(
            target: "operational_alert",
            alert = true,
            chain = %self.chain,
            symbol = %self.symbol,
            recovery_id = %self.recovery_id,
            %error,
            "Wrapped equity recovery requires operator intervention: active aggregate \
             validation failed; closing the detection and retaining any existing hold"
        );
        ctx.store
            .send(
                &self.recovery_id,
                WrappedEquityRecoveryCommand::FailInvalidDetection {
                    reason: error.to_string(),
                },
            )
            .await?;
        Ok(())
    }

    /// Fails a resumed `Detected` record whose premise no longer holds. The
    /// caller's guard drops to its claim origin. A fresh job reads the current
    /// balance without relying on another wallet snapshot event.
    async fn fail_stale_detected(
        &self,
        ctx: &WrappedEquityRecoveryCtx,
        reason: String,
    ) -> Result<(), WrappedEquityRecoveryJobError> {
        warn!(
            target: "rebalance",
            chain = %self.chain,
            symbol = %self.symbol,
            recovery_id = %self.recovery_id,
            %reason,
            "Failing stale detected wrapped equity recovery on resume",
        );
        ctx.store
            .send(
                &self.recovery_id,
                WrappedEquityRecoveryCommand::FailStaleDetection { reason },
            )
            .await?;
        self.enqueue_fresh_recovery(ctx).await
    }

    async fn enqueue_fresh_recovery(
        &self,
        ctx: &WrappedEquityRecoveryCtx,
    ) -> Result<(), WrappedEquityRecoveryJobError> {
        ctx.queue
            .clone()
            .push_idempotent_with_delay(
                &format!("wrapped-recovery-replacement:{}", self.recovery_id),
                Self {
                    recovery_id: WrappedEquityRecoveryId(uuid::Uuid::new_v4()),
                    ..self.clone()
                },
                ctx.reschedule_interval,
            )
            .await?;
        Ok(())
    }

    /// Sends the dispatch command for a detected recovery and settles the
    /// guard through `finish`.
    async fn dispatch(
        &self,
        ctx: &WrappedEquityRecoveryCtx,
        guard: RecoveryGuard,
        snapshot: RecoverySnapshot,
    ) -> Result<(), WrappedEquityRecoveryJobError> {
        let symbol = &self.symbol;
        let result = match snapshot.dispatch {
            DispatchDecision::ActiveMint(mint_id) => ctx
                .store
                .send(
                    &self.recovery_id,
                    WrappedEquityRecoveryCommand::DispatchToMint { mint_id },
                )
                .await
                .map_err(Into::into),
            DispatchDecision::ActiveRedemption(redemption_id) => ctx
                .store
                .send(
                    &self.recovery_id,
                    WrappedEquityRecoveryCommand::DispatchToRedemption { redemption_id },
                )
                .await
                .map_err(Into::into),
            DispatchDecision::Orphan => {
                ctx.store
                    .send(
                        &self.recovery_id,
                        WrappedEquityRecoveryCommand::SubmitOrphanDeposit,
                    )
                    .await?;
                if let Some(agg) = ctx.store.load(&self.recovery_id).await?
                    && agg.is_terminal()
                {
                    Ok(())
                } else {
                    ctx.store
                        .send(
                            &self.recovery_id,
                            WrappedEquityRecoveryCommand::ConfirmOrphanDeposit,
                        )
                        .await
                        .map_err(Into::into)
                }
            }
            // Rejected by `validate_active_aggregate_quantity` before
            // `Detect`; never dispatched across chains.
            DispatchDecision::BusyOnOtherChain {
                transfer,
                transfer_chain,
            } => Err(WrappedEquityRecoveryJobError::ActiveTransferOnOtherChain {
                symbol: symbol.clone(),
                transfer,
                transfer_chain,
                recovery_chain: self.chain,
            }),
            DispatchDecision::Conflict {
                mint_id,
                redemption_id,
            } => {
                let reason = format!(
                    "InventoryView reports active mint {mint_id} and active redemption \
                     {redemption_id} for symbol {symbol}; refusing to dispatch"
                );
                warn!(target: "rebalance", %symbol, %mint_id, %redemption_id, "Wrapped equity recovery: conflict");
                ctx.store
                    .send(
                        &self.recovery_id,
                        WrappedEquityRecoveryCommand::FailRecovery { reason },
                    )
                    .await?;
                // Aggregate is now terminal (FailRecovery). Release the guard
                // directly here so future transfers are not permanently blocked.
                guard.release();
                return Err(WrappedEquityRecoveryJobError::ConflictingActiveTransfers {
                    symbol: symbol.clone(),
                    mint_id,
                    redemption_id,
                });
            }
        };

        finish(ctx, self, guard, result).await
    }
}

/// Handles a dispatch that failed validation before `Detect`. The guard
/// drops either way, restoring its claim origin (orphan removes the entry;
/// `HeldForRecovery` restores `HeldForRecovery`).
async fn wait_or_retry_after_validation(
    ctx: &WrappedEquityRecoveryCtx,
    job: &WrappedEquityRecoveryJob,
    error: WrappedEquityRecoveryJobError,
) -> Result<(), WrappedEquityRecoveryJobError> {
    if let WrappedEquityRecoveryJobError::ActiveTransferOnOtherChain { .. } = error {
        // Another chain's transfer owns the symbol. Record nothing and wait:
        // dispatching would resume that transfer from this chain's recovery,
        // and the orphan path would treat its tokens as abandoned.
        error!(
            target: "operational_alert",
            alert = true,
            chain = %job.chain,
            symbol = %job.symbol,
            recovery_id = %job.recovery_id,
            %error,
            "Rescheduling wrapped equity recovery: the symbol's active transfer is \
             on another chain",
        );
        ctx.queue
            .clone()
            .push_with_delay(job.clone(), ctx.reschedule_interval)
            .await?;
        return Ok(());
    }

    warn!(
        target: "rebalance",
        symbol = %job.symbol,
        recovery_id = %job.recovery_id,
        %error,
        "Wrapped equity recovery: active aggregate quantity mismatch; \
         skipping dispatch",
    );
    // A quantity mismatch is retryable.
    Err(error)
}

/// Releases or restores the per-symbol guard based on the dispatch outcome
/// and, on a bot-gas enqueue failure, redrives `job` with a delay instead of
/// propagating the error terminally. Shared by the fresh-dispatch path and
/// the `OrphanDepositSubmitted` resume path so both apply the identical
/// success/redrive/failure handling.
async fn finish(
    ctx: &WrappedEquityRecoveryCtx,
    job: &WrappedEquityRecoveryJob,
    guard: RecoveryGuard,
    result: Result<(), WrappedEquityRecoveryJobError>,
) -> Result<(), WrappedEquityRecoveryJobError> {
    // Release the guard on success (removes the slot). On a bot-gas
    // bookkeeping failure the shared `redrive_on_bot_gas_failure` mechanism
    // redrives via `ctx.queue` without releasing the guard, so the slot
    // drops normally (an orphan-origin claim removes the entry, while a
    // HeldForRecovery-origin claim restores HeldForRecovery) exactly as any
    // other retryable failure would -- the confirm step the failure follows
    // already succeeded onchain and the aggregate has not advanced past it,
    // so redriving the same command is safe. A recovery whose chain has no
    // services reschedules the same way, keeping the guard's claim origin.
    // Any other failure propagates.
    match result {
        Ok(()) => {
            guard.release();
            Ok(())
        }
        Err(error) if error.is_mint_resume_pending() => {
            warn!(%error, "Mint recovery remains pending; retaining ownership and retrying");
            ctx.queue
                .clone()
                .push_with_delay(job.clone(), ctx.reschedule_interval)
                .await?;
            Ok(())
        }
        Err(error) if error.is_chain_services_missing() => {
            error!(
                target: "operational_alert",
                alert = true,
                chain = %job.chain,
                symbol = %job.symbol,
                recovery_id = %job.recovery_id,
                %error,
                "Wrapped equity recovery cannot run: its chain has no equity services; \
                 rescheduling until the chain is wired again",
            );
            ctx.queue
                .clone()
                .push_with_delay(job.clone(), ctx.reschedule_interval)
                .await?;
            Ok(())
        }
        Err(error) => {
            redrive_on_bot_gas_failure(job, &ctx.queue, ctx.reschedule_interval, error).await
        }
    }
}

/// Fails a recovery whose record names another chain than the job that
/// resumed it. Driving it would act on one chain's wallet from the other
/// chain's job, so the record is closed and a fresh detection starts over.
async fn fail_on_chain_mismatch(
    ctx: &WrappedEquityRecoveryCtx,
    job: &WrappedEquityRecoveryJob,
    recorded_chain: Chain,
) -> Result<(), WrappedEquityRecoveryJobError> {
    let reason = format!(
        "recovery is recorded on {recorded_chain} but its job runs on {}",
        job.chain
    );
    error!(
        target: "rebalance",
        symbol = %job.symbol,
        recovery_id = %job.recovery_id,
        %recorded_chain,
        job_chain = %job.chain,
        "Wrapped equity recovery: chain mismatch between record and job; failing recovery",
    );
    ctx.store
        .send(
            &job.recovery_id,
            WrappedEquityRecoveryCommand::FailRecovery { reason },
        )
        .await?;
    Ok(())
}

impl WrappedEquityRecoveryJobError {
    fn is_mint_resume_pending(&self) -> bool {
        matches!(
            self,
            Self::Aggregate(AggregateError::UserError(LifecycleError::Apply(
                WrappedEquityRecoveryError::MintResumePending { .. }
            ))) | Self::Domain(WrappedEquityRecoveryError::MintResumePending { .. })
        )
    }

    /// The active mint or redemption no longer matches the wallet snapshot.
    /// A resumed record closes without queuing another invalid detection.
    fn is_business_validation(&self) -> bool {
        match self {
            Self::ActiveMintQuantityMismatch { .. }
            | Self::ActiveRedemptionQuantityMismatch { .. }
            | Self::ActiveMintMissing { .. }
            | Self::ActiveRedemptionMissing { .. } => true,
            Self::Aggregate(_)
            | Self::Domain(_)
            | Self::ConflictingActiveTransfers { .. }
            | Self::ActiveTransferOnOtherChain { .. }
            | Self::ActiveMintAggregate(_)
            | Self::ActiveRedemptionAggregate(_)
            | Self::Reschedule(_) => false,
        }
    }

    fn is_chain_services_missing(&self) -> bool {
        match self {
            Self::Aggregate(AggregateError::UserError(LifecycleError::Apply(
                WrappedEquityRecoveryError::ChainServicesMissing(_),
            )))
            | Self::Domain(WrappedEquityRecoveryError::ChainServicesMissing(_)) => true,
            Self::Aggregate(_)
            | Self::Domain(_)
            | Self::ConflictingActiveTransfers { .. }
            | Self::ActiveMintQuantityMismatch { .. }
            | Self::ActiveRedemptionQuantityMismatch { .. }
            | Self::ActiveMintMissing { .. }
            | Self::ActiveRedemptionMissing { .. }
            | Self::ActiveTransferOnOtherChain { .. }
            | Self::ActiveMintAggregate(_)
            | Self::ActiveRedemptionAggregate(_)
            | Self::Reschedule(_) => false,
        }
    }
}

impl BotGasFailureClassifier for WrappedEquityRecoveryJobError {
    fn is_bot_gas_enqueue_failure(&self) -> bool {
        match self {
            Self::Aggregate(AggregateError::UserError(LifecycleError::Apply(
                WrappedEquityRecoveryError::BotGasEnqueueFailed(_),
            )))
            | Self::Domain(WrappedEquityRecoveryError::BotGasEnqueueFailed(_)) => true,
            Self::Aggregate(_)
            | Self::Domain(_)
            | Self::ConflictingActiveTransfers { .. }
            | Self::ActiveMintQuantityMismatch { .. }
            | Self::ActiveRedemptionQuantityMismatch { .. }
            | Self::ActiveMintMissing { .. }
            | Self::ActiveRedemptionMissing { .. }
            | Self::ActiveTransferOnOtherChain { .. }
            | Self::ActiveMintAggregate(_)
            | Self::ActiveRedemptionAggregate(_)
            | Self::Reschedule(_) => false,
        }
    }
}

struct RecoverySnapshot {
    shares: st0x_execution::FractionalShares,
    dispatch: DispatchDecision,
}

#[derive(Debug)]
enum DispatchDecision {
    ActiveMint(IssuerRequestId),
    ActiveRedemption(RedemptionAggregateId),
    Orphan,
    /// `InventoryView` reports both an active mint and an active redemption
    /// for the same symbol. A symbol can only be in one in-flight transfer
    /// at a time -- this is a corrupt-state signal, not a normal dispatch
    /// path.
    Conflict {
        mint_id: IssuerRequestId,
        redemption_id: RedemptionAggregateId,
    },
    /// The symbol's active mint or redemption runs on another chain. The
    /// symbol is busy: this chain's wallet balance is neither that
    /// transfer's tokens nor an orphan while it runs.
    BusyOnOtherChain {
        transfer: String,
        transfer_chain: Chain,
    },
}

async fn read_recovery_snapshot(
    inventory: &BroadcastingInventory,
    chain: Chain,
    symbol: &Symbol,
) -> Option<RecoverySnapshot> {
    let view = inventory.read().await;
    let shares = view.inflight_equity_at(symbol, InFlightEquityLocation::WalletWrapped(chain))?;
    if shares == st0x_execution::FractionalShares::ZERO {
        return None;
    }
    let dispatch = decide_dispatch(&view, chain, symbol);
    drop(view);
    Some(RecoverySnapshot { shares, dispatch })
}

/// Confirms the active mint or redemption aggregate carries the same quantity
/// as the wrapped wallet snapshot. Without this check, the recovery stream
/// would record `snapshot.shares` for an aggregate that was actually set up
/// for a different amount, leaving the audit trail and the resumed work
/// disagreeing on how many shares moved.
///
/// A `WrapSubmitted` mint is exempt from the quantity check: its quantity is
/// in underlying shares, while the landed wrap left vault shares in the
/// wallet, and the two differ whenever the vault ratio is not 1. Dispatch only
/// resumes the mint, which reads the wrap receipt and deposits the share count
/// it reports.
async fn validate_active_aggregate_quantity(
    ctx: &WrappedEquityRecoveryCtx,
    chain: Chain,
    symbol: &Symbol,
    snapshot: &RecoverySnapshot,
) -> Result<(), WrappedEquityRecoveryJobError> {
    match &snapshot.dispatch {
        DispatchDecision::ActiveMint(mint_id) => {
            let mint = ctx.mint_store.load(mint_id).await?.ok_or_else(|| {
                WrappedEquityRecoveryJobError::ActiveMintMissing {
                    symbol: symbol.clone(),
                    mint_id: mint_id.clone(),
                }
            })?;
            if mint.chain() != chain {
                return Err(WrappedEquityRecoveryJobError::ActiveTransferOnOtherChain {
                    symbol: symbol.clone(),
                    transfer: format!("mint {mint_id}"),
                    transfer_chain: mint.chain(),
                    recovery_chain: chain,
                });
            }
            if matches!(mint, TokenizedEquityMint::WrapSubmitted { .. }) {
                return Ok(());
            }
            let aggregate_shares = FractionalShares::new(mint.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(WrappedEquityRecoveryJobError::ActiveMintQuantityMismatch {
                    symbol: symbol.clone(),
                    mint_id: mint_id.clone(),
                    snapshot_shares: snapshot.shares,
                    aggregate_shares,
                });
            }
            Ok(())
        }
        DispatchDecision::ActiveRedemption(redemption_id) => {
            let redemption = ctx
                .redemption_store
                .load(redemption_id)
                .await?
                .ok_or_else(|| WrappedEquityRecoveryJobError::ActiveRedemptionMissing {
                    symbol: symbol.clone(),
                    redemption_id: redemption_id.clone(),
                })?;
            if redemption.chain() != chain {
                return Err(WrappedEquityRecoveryJobError::ActiveTransferOnOtherChain {
                    symbol: symbol.clone(),
                    transfer: format!("redemption {redemption_id}"),
                    transfer_chain: redemption.chain(),
                    recovery_chain: chain,
                });
            }
            let aggregate_shares = FractionalShares::new(redemption.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(
                    WrappedEquityRecoveryJobError::ActiveRedemptionQuantityMismatch {
                        symbol: symbol.clone(),
                        redemption_id: redemption_id.clone(),
                        snapshot_shares: snapshot.shares,
                        aggregate_shares,
                    },
                );
            }
            Ok(())
        }
        DispatchDecision::BusyOnOtherChain {
            transfer,
            transfer_chain,
        } => Err(WrappedEquityRecoveryJobError::ActiveTransferOnOtherChain {
            symbol: symbol.clone(),
            transfer: transfer.clone(),
            transfer_chain: *transfer_chain,
            recovery_chain: chain,
        }),
        DispatchDecision::Orphan | DispatchDecision::Conflict { .. } => Ok(()),
    }
}

/// Picks the dispatch path for a wallet balance on `chain`. Only a transfer
/// on the same chain can own that balance; a transfer of the symbol on
/// another chain makes the symbol busy rather than the balance an orphan.
fn decide_dispatch(view: &InventoryView, chain: Chain, symbol: &Symbol) -> DispatchDecision {
    if let (Some((mint_id, _)), Some((redemption_id, _))) = (
        view.active_mint_with_chain(symbol),
        view.active_redemption_with_chain(symbol),
    ) {
        return DispatchDecision::Conflict {
            mint_id: mint_id.clone(),
            redemption_id: redemption_id.clone(),
        };
    }

    if let Some((mint_id, mint_chain)) = view.active_mint_with_chain(symbol)
        && mint_chain != chain
    {
        return DispatchDecision::BusyOnOtherChain {
            transfer: format!("mint {mint_id}"),
            transfer_chain: mint_chain,
        };
    }

    if let Some((redemption_id, redemption_chain)) = view.active_redemption_with_chain(symbol)
        && redemption_chain != chain
    {
        return DispatchDecision::BusyOnOtherChain {
            transfer: format!("redemption {redemption_id}"),
            transfer_chain: redemption_chain,
        };
    }

    match (
        view.active_mint_on(symbol, chain),
        view.active_redemption_on(symbol, chain),
    ) {
        (Some(mint_id), Some(redemption_id)) => DispatchDecision::Conflict {
            mint_id: mint_id.clone(),
            redemption_id: redemption_id.clone(),
        },
        (Some(mint_id), None) => DispatchDecision::ActiveMint(mint_id.clone()),
        (None, Some(redemption_id)) => DispatchDecision::ActiveRedemption(redemption_id.clone()),
        (None, None) => DispatchDecision::Orphan,
    }
}

#[cfg(test)]
mod tests {
    use alloy::primitives::{Address, B256};
    use std::collections::BTreeMap;
    use std::sync::{Arc, RwLock};
    use tokio::sync::broadcast;
    use uuid::Uuid;

    use st0x_config::ChainEquities;
    use st0x_event_sorcery::test_store;
    use st0x_evm::Chain;
    use st0x_raindex::Raindex;
    use st0x_tokenization::mock::MockTokenizer;
    use st0x_wrapper::{MockWrapper, Wrapper};

    use super::super::aggregate::WrappedEquityRecoveryServices;
    use super::*;

    #[test]
    fn conflicting_transfers_on_different_chains_are_not_normal_contention() {
        let symbol = Symbol::new("AAPL").unwrap();
        let mint_id = st0x_tokenization::issuer_request_id("cross-chain-mint");
        let redemption_id =
            crate::equity_redemption::redemption_aggregate_id("cross-chain-redemption");
        let view = InventoryView::default()
            .set_active_mint(symbol.clone(), Chain::Base, mint_id.clone())
            .set_active_redemption(symbol.clone(), Chain::Ethereum, redemption_id.clone());
        for chain in [Chain::Base, Chain::Ethereum] {
            assert!(
                matches!(decide_dispatch(&view, chain, &symbol), DispatchDecision::Conflict { mint_id: mint, redemption_id: redemption } if mint == mint_id && redemption == redemption_id)
            );
        }
    }
    use crate::inventory::BroadcastingInventory;
    use crate::inventory::view::InventoryView;
    use crate::mint_authorization::ConfiguredMintAuthorizer;
    use crate::native_gas::ConfiguredGasReadiness;
    use crate::onchain::mock::MockRaindex;
    use crate::rebalancing::equity::ChainEquityServices;
    use crate::rebalancing::equity::{CrossVenueEquityTransfer, EquityTransferServices};
    use crate::vault_lookup::{MockVaultLookup, VaultLookup};

    #[test]
    fn wrapped_equity_recovery_job_payload_without_backpressure_streak_deserializes_to_zero() {
        let payload = serde_json::json!({
            "symbol": Symbol::new("AAPL").unwrap(),
            "recovery_id": WrappedEquityRecoveryId(Uuid::new_v4()),
        });

        let job: WrappedEquityRecoveryJob = serde_json::from_value(payload).unwrap();
        assert_eq!(job.backpressure_streak, BackpressureStreak::default());
    }

    #[test]
    fn wrapped_equity_recovery_job_payload_without_chain_runs_on_base() {
        let payload = serde_json::json!({
            "symbol": "AAPL",
            "recovery_id": "7f9c2ba4-e88f-4f61-8b56-3a5c1b4c7e21",
        });

        let job: WrappedEquityRecoveryJob = serde_json::from_value(payload).unwrap();

        assert_eq!(job.chain, Chain::Base);
        assert_eq!(
            job.label().as_str(),
            "WrappedEquityRecovery:base:AAPL:7f9c2ba4-e88f-4f61-8b56-3a5c1b4c7e21"
        );
    }

    /// A recovery ctx whose store carries `chains` alone, with a wrapped
    /// wallet balance of 5 AAPL on the inventory view.
    async fn ctx_over(
        chains: BTreeMap<Chain, ChainEquityServices>,
        equity_in_progress: HashMap<Symbol, GuardState>,
    ) -> WrappedEquityRecoveryCtx {
        let (pool, apalis_pool) = crate::test_utils::setup_test_pools().await;
        let equity = EquityTransferServices {
            chains,
            bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
        };
        let mint_store = Arc::new(test_store(pool.clone(), equity.clone()));
        let redemption_store = Arc::new(test_store(pool.clone(), equity.clone()));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            equity.clone(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        let store = Arc::new(test_store(
            pool,
            WrappedEquityRecoveryServices {
                equity,
                transfer,
                bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
            },
        ));

        let now = chrono::Utc::now();
        let view = InventoryView::default().set_inflight_equity_at_location(
            InFlightEquityLocation::WalletWrapped(Chain::Base),
            &BTreeMap::from([(
                Symbol::new("AAPL").unwrap(),
                FractionalShares::new(st0x_float_macro::float!(5)),
            )]),
            now,
            now,
        );
        let (sender, _receiver) = broadcast::channel(16);

        WrappedEquityRecoveryCtx {
            inventory: Arc::new(BroadcastingInventory::new(view, sender)),
            store,
            mint_store,
            redemption_store,
            equity_in_progress: Arc::new(RwLock::new(equity_in_progress)),
            queue: WrappedEquityRecoveryJobQueue::new(&apalis_pool),
            reschedule_interval: Duration::from_secs(1),
        }
    }

    fn base_only_chain_services() -> BTreeMap<Chain, ChainEquityServices> {
        BTreeMap::from([(
            Chain::Base,
            ChainEquityServices {
                wallet: Address::ZERO,
                raindex: Arc::new(MockRaindex::new()),
                vault_lookup: Arc::new(
                    MockVaultLookup::new()
                        .with_default_vault(st0x_raindex::RaindexVaultId(B256::ZERO)),
                ),
                tokenizer: Arc::new(MockTokenizer::new()),
                wrapper: Arc::new(MockWrapper::new()),
                mint_authorizer: ConfiguredMintAuthorizer::Disabled,
                gas_readiness: ConfiguredGasReadiness::Unwired,
                equities: ChainEquities::default(),
            },
        )])
    }

    async fn queued_recovery_jobs(ctx: &WrappedEquityRecoveryCtx) -> Vec<WrappedEquityRecoveryJob> {
        let payloads: Vec<Vec<u8>> =
            sqlx_apalis::query_scalar("SELECT CAST(job AS TEXT) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<WrappedEquityRecoveryJob>())
                .fetch_all(ctx.queue.pool())
                .await
                .unwrap();
        payloads
            .iter()
            .map(|payload| serde_json::from_slice(payload).unwrap())
            .collect()
    }

    /// A job on a chain with no services opens no recovery and reschedules
    /// itself, and the symbol stays held for that chain's recovery while it
    /// waits.
    #[tokio::test]
    #[tracing_test::traced_test]
    async fn job_on_a_chain_without_services_reschedules_and_keeps_its_hold() {
        let symbol = Symbol::new("AAPL").unwrap();
        let held = GuardState::HeldForRecovery {
            chain: Chain::Ethereum,
        };
        let ctx = ctx_over(
            base_only_chain_services(),
            HashMap::from([(symbol.clone(), held.clone())]),
        )
        .await;
        let now = chrono::Utc::now();
        {
            let mut inventory = ctx.inventory.write().await;
            *inventory = inventory.clone().set_inflight_equity_at_location(
                InFlightEquityLocation::WalletWrapped(Chain::Ethereum),
                &BTreeMap::from([(
                    symbol.clone(),
                    FractionalShares::new(st0x_float_macro::float!(5)),
                )]),
                now,
                now,
            );
        }
        let job = WrappedEquityRecoveryJob {
            chain: Chain::Ethereum,
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
            backpressure_streak: BackpressureStreak::default(),
        };

        job.perform(&ctx).await.unwrap();
        assert!(logs_contain(
            "Wrapped equity recovery cannot run: its chain has no equity services"
        ));

        assert_eq!(ctx.store.load(&job.recovery_id).await.unwrap(), None);
        let rescheduled = queued_recovery_jobs(&ctx).await;
        assert_eq!(rescheduled.len(), 1, "the job must reschedule itself");
        assert_eq!(rescheduled[0].chain, Chain::Ethereum);
        assert_eq!(rescheduled[0].recovery_id, job.recovery_id);
        assert_eq!(
            ctx.equity_in_progress.read().unwrap().get(&symbol),
            Some(&held)
        );
    }

    /// A job resuming a recovery recorded on another chain must not drive it
    /// with its own chain's services: the recovery is failed, naming both.
    #[tokio::test]
    async fn job_whose_recovery_is_recorded_on_another_chain_fails_it() {
        let symbol = Symbol::new("AAPL").unwrap();
        let held = GuardState::HeldForRecovery { chain: Chain::Base };
        let mut chains = base_only_chain_services();
        let base = chains[&Chain::Base].clone();
        chains.insert(Chain::Ethereum, base);
        let ctx = ctx_over(chains, HashMap::from([(symbol.clone(), held.clone())])).await;
        let recovery_id = WrappedEquityRecoveryId(Uuid::new_v4());
        ctx.store
            .send(
                &recovery_id,
                WrappedEquityRecoveryCommand::Detect {
                    chain: Chain::Base,
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(st0x_float_macro::float!(5)),
                },
            )
            .await
            .unwrap();
        let job = WrappedEquityRecoveryJob {
            chain: Chain::Ethereum,
            symbol: symbol.clone(),
            recovery_id: recovery_id.clone(),
            backpressure_streak: BackpressureStreak::default(),
        };

        job.perform(&ctx).await.unwrap();

        let Some(WrappedEquityRecovery::Failed { chain, reason, .. }) =
            ctx.store.load(&recovery_id).await.unwrap()
        else {
            panic!("the mismatched recovery must be failed");
        };
        assert_eq!(chain, Chain::Base);
        assert_eq!(
            reason,
            "recovery is recorded on base but its job runs on ethereum"
        );
        assert_eq!(
            ctx.equity_in_progress.read().unwrap().get(&symbol),
            Some(&held)
        );
        assert_eq!(queued_recovery_jobs(&ctx).await.len(), 0);
    }

    /// A Base recovery must not dispatch to the symbol's active mint on
    /// another chain: it sends no `Detect` and reschedules until that
    /// transfer finishes.
    #[tokio::test]
    #[tracing_test::traced_test]
    async fn recovery_waits_for_an_active_mint_on_another_chain() {
        let symbol = Symbol::new("AAPL").unwrap();
        let held = GuardState::HeldForRecovery { chain: Chain::Base };
        let mut ctx = ctx_over(
            base_only_chain_services(),
            HashMap::from([(symbol.clone(), held.clone())]),
        )
        .await;
        let mint_id = st0x_tokenization::issuer_request_id("ISS-ETH");
        let view = ctx.inventory.read().await.clone().set_active_mint(
            symbol.clone(),
            Chain::Ethereum,
            mint_id.clone(),
        );
        let (sender, _receiver) = broadcast::channel(16);
        ctx.inventory = Arc::new(BroadcastingInventory::new(view, sender));
        ctx.mint_store
            .send(
                &mint_id,
                crate::tokenized_equity_mint::TokenizedEquityMintCommand::RequestMint {
                    chain: Chain::Ethereum,
                    issuer_request_id: mint_id.clone(),
                    symbol: symbol.clone(),
                    quantity: st0x_float_macro::float!(5),
                    wallet: Address::random(),
                },
            )
            .await
            .unwrap();
        let job = WrappedEquityRecoveryJob {
            chain: Chain::Base,
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
            backpressure_streak: BackpressureStreak::default(),
        };

        job.perform(&ctx).await.unwrap();
        assert!(logs_contain("operational_alert"));
        assert!(logs_contain("on another chain"));

        assert_eq!(ctx.store.load(&job.recovery_id).await.unwrap(), None);
        let rescheduled = queued_recovery_jobs(&ctx).await;
        assert_eq!(rescheduled.len(), 1, "the job must reschedule itself");
        assert_eq!(rescheduled[0].recovery_id, job.recovery_id);
        assert_eq!(
            ctx.equity_in_progress.read().unwrap().get(&symbol),
            Some(&held)
        );
    }

    /// A balance in Robinhood's wallet is never handed to Base's active mint
    /// nor taken as an orphan: the mint owns the symbol, so Robinhood's
    /// recovery records nothing and waits. The mint is never even loaded,
    /// because the view already names its chain.
    #[tokio::test]
    async fn another_chains_wallet_balance_waits_for_an_active_base_mint() {
        let symbol = Symbol::new("AAPL").unwrap();
        let mut chains = base_only_chain_services();
        let robinhood = chains[&Chain::Base].clone();
        chains.insert(Chain::Robinhood, robinhood);
        let mut ctx = ctx_over(chains, HashMap::new()).await;
        let now = chrono::Utc::now();
        let view = ctx
            .inventory
            .read()
            .await
            .clone()
            .set_inflight_equity_at_location(
                InFlightEquityLocation::WalletWrapped(Chain::Robinhood),
                &BTreeMap::from([(
                    symbol.clone(),
                    FractionalShares::new(st0x_float_macro::float!(5)),
                )]),
                now,
                now,
            )
            .set_active_mint(
                symbol.clone(),
                Chain::Base,
                st0x_tokenization::issuer_request_id("ISS-BASE"),
            );
        let (sender, _receiver) = broadcast::channel(16);
        ctx.inventory = Arc::new(BroadcastingInventory::new(view, sender));
        let job = WrappedEquityRecoveryJob {
            chain: Chain::Robinhood,
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
            backpressure_streak: BackpressureStreak::default(),
        };

        job.perform(&ctx).await.unwrap();

        assert_eq!(ctx.store.load(&job.recovery_id).await.unwrap(), None);
        let rescheduled = queued_recovery_jobs(&ctx).await;
        assert_eq!(rescheduled.len(), 1, "the job must reschedule itself");
        assert_eq!(rescheduled[0].chain, Chain::Robinhood);
        assert_eq!(ctx.equity_in_progress.read().unwrap().get(&symbol), None);
    }

    #[tokio::test]
    async fn guard_contention_reschedules_without_dropping_the_recovery() {
        let symbol = Symbol::new("AAPL").unwrap();
        let equity_in_progress = Arc::new(RwLock::new(HashMap::from([(
            symbol.clone(),
            GuardState::ActiveTransfer {
                generation: crate::rebalancing::trigger::GuardGeneration::default(),
            },
        )])));

        let (pool, apalis_pool) = crate::test_utils::setup_test_pools().await;

        let raindex: Arc<dyn Raindex> = Arc::new(MockRaindex::new());
        let vault_lookup: Arc<dyn VaultLookup> = Arc::new(MockVaultLookup::new());
        let wrapper: Arc<dyn Wrapper> = Arc::new(MockWrapper::new());
        let chain_services = ChainEquityServices {
            wallet: Address::ZERO,
            raindex: raindex.clone(),
            vault_lookup: vault_lookup.clone(),
            tokenizer: Arc::new(MockTokenizer::new()),
            wrapper: wrapper.clone(),
            mint_authorizer: ConfiguredMintAuthorizer::Disabled,
            gas_readiness: ConfiguredGasReadiness::Unwired,
            equities: ChainEquities::default(),
        };
        let transfer_services = EquityTransferServices {
            chains: BTreeMap::from([(Chain::Base, chain_services.clone())]),
            bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
        };
        let mint_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let redemption_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            transfer_services.clone(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        let store = Arc::new(test_store(
            pool.clone(),
            WrappedEquityRecoveryServices {
                equity: EquityTransferServices {
                    chains: BTreeMap::from([(Chain::Base, chain_services)]),
                    bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
                },
                transfer,
                bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
            },
        ));

        let (sender, _receiver) = broadcast::channel(16);
        let inventory = Arc::new(BroadcastingInventory::new(InventoryView::default(), sender));
        let ctx = WrappedEquityRecoveryCtx {
            inventory,
            store,
            mint_store,
            redemption_store,
            equity_in_progress,
            queue: WrappedEquityRecoveryJobQueue::new(&apalis_pool),
            reschedule_interval: Duration::from_secs(1),
        };
        let job = WrappedEquityRecoveryJob {
            chain: Chain::Base,
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
            backpressure_streak: BackpressureStreak::default(),
        };

        job.perform(&ctx).await.unwrap();

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            state.is_none(),
            "guard-held perform() must not start recovery; aggregate should be absent, got {state:?}",
        );

        let (rescheduled,): (i64,) =
            sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<WrappedEquityRecoveryJob>())
                .fetch_one(ctx.queue.pool())
                .await
                .unwrap();
        assert_eq!(
            rescheduled, 1,
            "guard contention must reschedule the wrapped recovery job, not mark it done",
        );
    }

    /// A job retried after `Detect` succeeded but before dispatch resumes
    /// from `Detected` instead of re-sending `Detect`, so the recovery
    /// reaches a terminal state.
    #[tokio::test]
    async fn retried_job_resumes_a_detected_recovery_to_terminal() {
        let ctx = ctx_over(base_only_chain_services(), HashMap::new()).await;
        let job = WrappedEquityRecoveryJob {
            chain: Chain::Base,
            symbol: Symbol::new("AAPL").unwrap(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
            backpressure_streak: BackpressureStreak::default(),
        };
        ctx.store
            .send(
                &job.recovery_id,
                WrappedEquityRecoveryCommand::Detect {
                    chain: Chain::Base,
                    symbol: job.symbol.clone(),
                    shares: FractionalShares::new(st0x_float_macro::float!(5)),
                },
            )
            .await
            .unwrap();

        job.perform(&ctx).await.unwrap();

        let state = ctx.store.load(&job.recovery_id).await.unwrap().unwrap();
        assert!(
            matches!(state, WrappedEquityRecovery::OrphanDeposited { .. }),
            "a detected recovery must resume to its orphan deposit, got {state:?}"
        );
    }

    /// A detected recovery whose wrapped balance is gone can never dispatch,
    /// so the retried job fails it instead of leaving it open.
    #[tokio::test]
    async fn retried_job_fails_a_detected_recovery_whose_balance_is_gone() {
        let mut ctx = ctx_over(base_only_chain_services(), HashMap::new()).await;
        let (sender, _receiver) = broadcast::channel(16);
        ctx.inventory = Arc::new(BroadcastingInventory::new(InventoryView::default(), sender));
        let job = WrappedEquityRecoveryJob {
            chain: Chain::Base,
            symbol: Symbol::new("AAPL").unwrap(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
            backpressure_streak: BackpressureStreak::default(),
        };
        ctx.store
            .send(
                &job.recovery_id,
                WrappedEquityRecoveryCommand::Detect {
                    chain: Chain::Base,
                    symbol: job.symbol.clone(),
                    shares: FractionalShares::new(st0x_float_macro::float!(5)),
                },
            )
            .await
            .unwrap();

        job.perform(&ctx).await.unwrap();

        let state = ctx.store.load(&job.recovery_id).await.unwrap().unwrap();
        assert!(
            matches!(state, WrappedEquityRecovery::Failed { .. }),
            "a detected recovery with no balance must fail, got {state:?}"
        );
        assert!(ctx.equity_in_progress.read().unwrap().is_empty());
    }

    /// A resumed `Detected` record deposits its stored shares, so a changed
    /// wallet balance fails it rather than depositing the wrong amount.
    #[tokio::test]
    async fn retried_job_fails_a_detected_recovery_whose_shares_changed() {
        for held in [false, true] {
            let symbol = Symbol::new("AAPL").unwrap();
            let ownership = if held {
                HashMap::from([(symbol, GuardState::HeldForRecovery { chain: Chain::Base })])
            } else {
                HashMap::new()
            };
            let mut ctx = ctx_over(base_only_chain_services(), ownership).await;
            let apalis_pool = crate::test_utils::setup_test_apalis_pool().await;
            ctx.queue = WrappedEquityRecoveryJobQueue::new(&apalis_pool);
            let job = WrappedEquityRecoveryJob {
                chain: Chain::Base,
                symbol: Symbol::new("AAPL").unwrap(),
                recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
                backpressure_streak: BackpressureStreak::default(),
            };
            ctx.store
                .send(
                    &job.recovery_id,
                    WrappedEquityRecoveryCommand::Detect {
                        chain: Chain::Base,
                        symbol: job.symbol.clone(),
                        shares: FractionalShares::new(st0x_float_macro::float!(3)),
                    },
                )
                .await
                .unwrap();

            if held {
                let closed_pool = crate::test_utils::setup_test_apalis_pool().await;
                closed_pool.close().await;
                ctx.queue = WrappedEquityRecoveryJobQueue::new(&closed_pool);
                assert!(matches!(
                    job.perform(&ctx).await.unwrap_err(),
                    WrappedEquityRecoveryJobError::Reschedule(_)
                ));
                ctx.queue = WrappedEquityRecoveryJobQueue::new(&apalis_pool);
            }
            job.perform(&ctx).await.unwrap();
            job.perform(&ctx).await.unwrap();

            let (queued,): (i64,) = sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs")
                .fetch_one(&apalis_pool)
                .await
                .unwrap();
            assert_eq!(queued, 1);

            let state = ctx.store.load(&job.recovery_id).await.unwrap().unwrap();
            assert!(
                matches!(state, WrappedEquityRecovery::Failed { .. }),
                "a detected recovery whose balance changed must fail, got {state:?}"
            );
            let (payload,): (String,) =
                sqlx_apalis::query_as("SELECT CAST(job AS TEXT) FROM Jobs WHERE job_type = ?")
                    .bind(std::any::type_name::<WrappedEquityRecoveryJob>())
                    .fetch_one(&apalis_pool)
                    .await
                    .unwrap();
            let fresh: WrappedEquityRecoveryJob = serde_json::from_str(&payload).unwrap();
            assert_eq!(fresh.chain, job.chain);
            assert_eq!(fresh.symbol, job.symbol);
            assert_ne!(fresh.recovery_id, job.recovery_id);
            assert_eq!(
                ctx.equity_in_progress
                    .read()
                    .unwrap()
                    .contains_key(&job.symbol),
                held
            );
        }
    }

    /// Invalid dispatch needs operator intervention, not another detection.
    #[tokio::test]
    #[tracing_test::traced_test]
    async fn missing_active_mint_closes_detection_and_preserves_hold_without_replacement() {
        let held = GuardState::HeldForRecovery { chain: Chain::Base };
        let mut ctx = ctx_over(
            base_only_chain_services(),
            HashMap::from([(Symbol::new("AAPL").unwrap(), held.clone())]),
        )
        .await;
        let symbol = Symbol::new("AAPL").unwrap();
        let now = chrono::Utc::now();
        let balances = BTreeMap::from([(
            symbol.clone(),
            FractionalShares::new(st0x_float_macro::float!(5)),
        )]);
        let view = InventoryView::default()
            .set_inflight_equity_at_location(
                InFlightEquityLocation::WalletWrapped(Chain::Base),
                &balances,
                now,
                now,
            )
            .set_active_mint(
                symbol.clone(),
                Chain::Base,
                st0x_tokenization::issuer_request_id("missing-mint"),
            );
        let (sender, _receiver) = broadcast::channel(16);
        ctx.inventory = Arc::new(BroadcastingInventory::new(view, sender));
        let job = WrappedEquityRecoveryJob {
            chain: Chain::Base,
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
            backpressure_streak: BackpressureStreak::default(),
        };
        ctx.store
            .send(
                &job.recovery_id,
                WrappedEquityRecoveryCommand::Detect {
                    chain: Chain::Base,
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(st0x_float_macro::float!(5)),
                },
            )
            .await
            .unwrap();

        job.perform(&ctx).await.unwrap();
        job.perform(&ctx).await.unwrap();
        assert_eq!(queued_recovery_jobs(&ctx).await.len(), 0);
        assert!(logs_contain("requires operator intervention"));
        assert_eq!(
            ctx.equity_in_progress.read().unwrap().get(&symbol),
            Some(&held)
        );

        let state = ctx.store.load(&job.recovery_id).await.unwrap().unwrap();
        assert!(
            matches!(
                state,
                WrappedEquityRecovery::Failed {
                    detection_failure: Some(DetectionFailureDisposition::PreserveHold),
                    ..
                }
            ),
            "a missing active mint must close its detection, got {state:?}"
        );
    }

    #[tokio::test]
    async fn enqueue_dedup_matches_symbol_exactly_not_as_substring() {
        let apalis_pool = crate::test_utils::setup_test_apalis_pool().await;

        let mut queue = WrappedEquityRecoveryJobQueue::new(&apalis_pool);
        queue
            .push(WrappedEquityRecoveryJob {
                chain: Chain::Base,
                symbol: Symbol::new("GOOGL").unwrap(),
                recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
                backpressure_streak: BackpressureStreak::default(),
            })
            .await
            .unwrap();

        // The exact query the reactor uses to dedupe wrapped-recovery enqueues.
        const DEDUP_QUERY: &str = "SELECT COUNT(*) FROM Jobs \
             WHERE job_type = ? \
             AND status IN ('Pending', 'Queued', 'Running') \
             AND json_extract(job, '$.symbol') = ?";
        let job_type = std::any::type_name::<WrappedEquityRecoveryJob>();

        let (exact,): (i64,) = sqlx_apalis::query_as(DEDUP_QUERY)
            .bind(job_type)
            .bind("GOOGL")
            .fetch_one(&apalis_pool)
            .await
            .unwrap();
        assert_eq!(exact, 1, "exact symbol must match the queued GOOGL job");

        let (substring,): (i64,) = sqlx_apalis::query_as(DEDUP_QUERY)
            .bind(job_type)
            .bind("GOOG")
            .fetch_one(&apalis_pool)
            .await
            .unwrap();
        assert_eq!(
            substring, 0,
            "a substring ticker (GOOG) must not match the queued GOOGL job",
        );
    }

    /// Acceptance criterion (ADR 0017 SS4): a bot-gas receipt cost enqueue
    /// failure on `ConfirmOrphanDeposit` must delayed-redrive the job rather
    /// than propagate terminally -- otherwise a bookkeeping write can consume
    /// the apalis retry budget and open this supervised worker's fail-stop
    /// circuit. The confirm already succeeded on-chain and the aggregate has
    /// not advanced past `OrphanDepositSubmitted`, so redriving is safe.
    #[tokio::test]
    async fn confirm_orphan_deposit_bot_gas_enqueue_failure_redrives_without_terminal_error() {
        let symbol = Symbol::new("AAPL").unwrap();
        let equity_in_progress = Arc::new(RwLock::new(HashMap::new()));

        let (pool, apalis_pool) = crate::test_utils::setup_test_pools().await;
        let closed_apalis_pool = crate::test_utils::setup_test_apalis_pool().await;
        closed_apalis_pool.close().await;
        let bot_gas_queue =
            crate::bot_gas::RecordBotGasReceiptCostJobQueue::new(&closed_apalis_pool);

        let raindex: Arc<dyn Raindex> = Arc::new(MockRaindex::new());
        let vault_lookup: Arc<dyn VaultLookup> = Arc::new(
            MockVaultLookup::new()
                .with_vault(Address::ZERO, st0x_raindex::RaindexVaultId(B256::ZERO))
                .with_default_vault(st0x_raindex::RaindexVaultId(B256::ZERO)),
        );
        let wrapper: Arc<dyn Wrapper> = Arc::new(MockWrapper::new());
        let chain_services = ChainEquityServices {
            wallet: Address::ZERO,
            raindex: raindex.clone(),
            vault_lookup: vault_lookup.clone(),
            tokenizer: Arc::new(MockTokenizer::new()),
            wrapper: wrapper.clone(),
            mint_authorizer: ConfiguredMintAuthorizer::Disabled,
            gas_readiness: ConfiguredGasReadiness::Unwired,
            equities: ChainEquities::default(),
        };
        let transfer_services = EquityTransferServices {
            chains: BTreeMap::from([(Chain::Base, chain_services.clone())]),
            bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
        };
        let mint_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let redemption_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            transfer_services.clone(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        // The store's bot-gas enqueuer targets the CLOSED pool so
        // `ConfirmOrphanDeposit`'s enqueue fails with a genuine
        // `QueuePushError`. `SubmitOrphanDeposit` (used to seed state below)
        // never calls the enqueuer, so seeding is unaffected.
        let store = Arc::new(test_store(
            pool.clone(),
            WrappedEquityRecoveryServices {
                equity: EquityTransferServices {
                    chains: BTreeMap::from([(Chain::Base, chain_services)]),
                    bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
                },
                transfer,
                bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Enabled(bot_gas_queue),
            },
        ));

        let (sender, _receiver) = broadcast::channel(16);
        let mut balances = std::collections::BTreeMap::new();
        balances.insert(
            symbol.clone(),
            st0x_execution::FractionalShares::new(st0x_float_macro::float!(5)),
        );
        let now = chrono::Utc::now();
        let view = InventoryView::default().set_inflight_equity_at_location(
            crate::inventory::view::InFlightEquityLocation::WalletWrapped(Chain::Base),
            &balances,
            now,
            now,
        );
        let inventory = Arc::new(BroadcastingInventory::new(view, sender));

        let ctx = WrappedEquityRecoveryCtx {
            inventory,
            store: store.clone(),
            mint_store,
            redemption_store,
            equity_in_progress,
            queue: WrappedEquityRecoveryJobQueue::new(&apalis_pool),
            reschedule_interval: Duration::from_secs(1),
        };
        let recovery_id = WrappedEquityRecoveryId(Uuid::new_v4());

        store
            .send(
                &recovery_id,
                WrappedEquityRecoveryCommand::Detect {
                    chain: Chain::Base,
                    symbol: symbol.clone(),
                    shares: st0x_execution::FractionalShares::new(st0x_float_macro::float!(5)),
                },
            )
            .await
            .unwrap();
        store
            .send(
                &recovery_id,
                WrappedEquityRecoveryCommand::SubmitOrphanDeposit,
            )
            .await
            .unwrap();
        let seeded = store.load(&recovery_id).await.unwrap();
        assert!(
            matches!(
                seeded,
                Some(WrappedEquityRecovery::OrphanDepositSubmitted { .. })
            ),
            "seeding should land in OrphanDepositSubmitted, got {seeded:?}",
        );

        let job = WrappedEquityRecoveryJob {
            chain: Chain::Base,
            symbol: symbol.clone(),
            recovery_id: recovery_id.clone(),
            backpressure_streak: BackpressureStreak::default(),
        };

        job.perform(&ctx)
            .await
            .expect("a bot-gas enqueue failure must not fail the recovery job terminally");

        let state = store.load(&recovery_id).await.unwrap();
        assert!(
            matches!(
                state,
                Some(WrappedEquityRecovery::OrphanDepositSubmitted { .. })
            ),
            "the aggregate must remain un-advanced (ConfirmOrphanDeposit did not commit), \
             got {state:?}",
        );

        let (rescheduled,): (i64,) =
            sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<WrappedEquityRecoveryJob>())
                .fetch_one(&apalis_pool)
                .await
                .unwrap();
        assert_eq!(
            rescheduled, 1,
            "a bot-gas enqueue failure must re-enqueue a delayed replacement job",
        );
    }
}
