//! Apalis job that orchestrates wrapped-equity recovery.
//!
//! Enqueued per symbol with a positive `BaseWalletWrappedEquity` balance.
//! The job performs the recovery's side effects (raindex deposit/confirm,
//! mint/redemption resume, wrapped-token lookup) and records each outcome
//! through the aggregate's pure commands. The aggregate is a pure state
//! machine (`Services = ()`); all I/O lives here.
//!
//! Steps:
//!
//! 1. Claim the `equity_in_progress` guard for the symbol (from absent or
//!    `HeldForRecovery`). If a live transfer owns it (`ActiveTransfer`), the
//!    job reschedules itself with a delay so an unchanged wallet balance is
//!    not stranded waiting for another snapshot.
//! 2. Resume from the persisted aggregate state so a retry picks up where the
//!    previous attempt stopped: fresh (`Detect` -> dispatch), `Detected`
//!    (re-dispatch), or `OrphanDepositSubmitted` (re-confirm the deposit).
//!    Resuming from the persisted deposit tx hash rather than re-running
//!    `submit_deposit` is what keeps a retry from double-depositing -- but only
//!    once `OrphanDepositSubmitted` has landed. A crash after `submit_deposit`
//!    returns but before that event is persisted re-runs `submit_deposit` on
//!    resume (a second on-chain deposit); this dual-write window is
//!    architecturally unavoidable and matches the prior atomic-handler design.
//! 3. For the chosen dispatch path, run the I/O and send the matching pure
//!    command: `DispatchToMint` / `DispatchToRedemption`, or the orphan
//!    `SubmitOrphanDeposit { tx } -> ConfirmOrphanDeposit` sequence. A terminal
//!    service failure is recorded via `FailRecovery`; a transient deposit
//!    confirmation failure surfaces as a job error so apalis retries from the
//!    persisted `OrphanDepositSubmitted`.
//!
//! The job carries its `WrappedEquityRecoveryId` in the apalis payload
//! (generated by the reactor when pushing the job) so retries target the
//! same aggregate.

use alloy::primitives::TxHash;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, RwLock};
use std::time::Duration;
use thiserror::Error;
use tracing::{debug, info, warn};

use st0x_event_sorcery::{SendError, Store};
use st0x_execution::{FractionalShares, Symbol};
use st0x_tokenization::IssuerRequestId;

use super::aggregate::{
    WrappedEquityRecovery, WrappedEquityRecoveryCommand, WrappedEquityRecoveryError,
    WrappedEquityRecoveryId, WrappedEquityRecoveryServices,
};
use crate::conductor::job::{Job, JobQueue, Label, QueuePushError};
use crate::equity_redemption::{EquityRedemption, RedemptionAggregateId};
use crate::inventory::BroadcastingInventory;
use crate::inventory::view::{InFlightEquityLocation, InventoryView};
use crate::rebalancing::trigger::{GuardState, claim_guard_for_recovery_or_orphan};
use crate::tokenized_equity_mint::{TOKENIZED_EQUITY_DECIMALS, TokenizedEquityMint};

/// Apalis queue type for [`WrappedEquityRecoveryJob`].
pub(crate) type WrappedEquityRecoveryJobQueue = JobQueue<WrappedEquityRecoveryJob>;

/// Dependencies the recovery job needs to claim the per-symbol concurrency
/// guard, read inventory, perform the recovery's onchain/transfer side effects,
/// and record outcomes through the aggregate's pure command store.
pub(crate) struct WrappedEquityRecoveryCtx {
    pub(crate) inventory: Arc<BroadcastingInventory>,
    pub(crate) store: Arc<Store<WrappedEquityRecovery>>,
    /// Onchain/transfer dependencies the job drives before recording outcomes.
    pub(crate) services: WrappedEquityRecoveryServices,
    pub(crate) mint_store: Arc<Store<TokenizedEquityMint>>,
    pub(crate) redemption_store: Arc<Store<EquityRedemption>>,
    pub(crate) equity_in_progress: Arc<RwLock<HashMap<Symbol, GuardState>>>,
    /// Queue used for delayed self-reschedule when the shared equity guard is
    /// held by another recovery/transfer job.
    pub(crate) queue: WrappedEquityRecoveryJobQueue,
    pub(crate) reschedule_interval: Duration,
}

/// Why a single recovery job attempt failed. Errors propagate up through
/// apalis. A terminal service failure is recorded as a `RecoveryFailed` event
/// (the attempt returns `Ok`); only retryable failures and business-validation
/// failures surface here.
#[derive(Debug, Error)]
pub(crate) enum WrappedEquityRecoveryJobError {
    #[error("recovery aggregate error: {0}")]
    Aggregate(#[from] SendError<WrappedEquityRecovery>),
    #[error(transparent)]
    Domain(#[from] WrappedEquityRecoveryError),
    #[error(
        "active mint {mint_id} for symbol {symbol} carries quantity {aggregate_shares}, \
         which does not match the wrapped-equity wallet snapshot {snapshot_shares} -- \
         refusing to dispatch to a stale aggregate"
    )]
    ActiveMintQuantityMismatch {
        symbol: Symbol,
        mint_id: IssuerRequestId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },
    #[error(
        "active redemption {redemption_id} for symbol {symbol} carries quantity \
         {aggregate_shares}, which does not match the wrapped-equity wallet snapshot \
         {snapshot_shares} -- refusing to dispatch to a stale aggregate"
    )]
    ActiveRedemptionQuantityMismatch {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },
    #[error("active mint {mint_id} for symbol {symbol} is missing from the mint store")]
    ActiveMintMissing {
        symbol: Symbol,
        mint_id: IssuerRequestId,
    },
    #[error(
        "active redemption {redemption_id} for symbol {symbol} is missing from the \
         redemption store"
    )]
    ActiveRedemptionMissing {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
    },
    #[error("active mint store error: {0}")]
    ActiveMintAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::tokenized_equity_mint::TokenizedEquityMint>,
        >,
    ),
    #[error("active redemption store error: {0}")]
    ActiveRedemptionAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::equity_redemption::EquityRedemption>,
        >,
    ),
    #[error(
        "inventory reports no positive wrapped balance for symbol {symbol}; nothing to recover \
         this cycle"
    )]
    NoBalanceSkip { symbol: Symbol },
    #[error(
        "deposit {vault_deposit_tx_hash} was submitted but not yet confirmable; retry from the \
         persisted OrphanDepositSubmitted state"
    )]
    RetryableDepositConfirmation { vault_deposit_tx_hash: TxHash },
    #[error("failed to reschedule recovery job after guard contention: {0}")]
    Reschedule(#[from] QueuePushError),
}

/// Apalis job payload. The reactor pushes one of these per symbol with a
/// positive `BaseWalletWrappedEquity` balance, generating a fresh
/// `recovery_id` at push time so apalis retries hit the same aggregate.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub(crate) struct WrappedEquityRecoveryJob {
    pub(crate) symbol: Symbol,
    pub(crate) recovery_id: WrappedEquityRecoveryId,
}

impl Job<WrappedEquityRecoveryCtx> for WrappedEquityRecoveryJob {
    type Output = ();
    type Error = WrappedEquityRecoveryJobError;

    const WORKER_NAME: &'static str = "wrapped-equity-recovery-worker";

    #[cfg(any(test, feature = "test-support"))]
    const JOB_KIND: crate::conductor::job::JobKind =
        crate::conductor::job::JobKind::WrappedEquityRecovery;

    fn label(&self) -> Label {
        Label::new(format!(
            "WrappedEquityRecovery:{}:{}",
            self.symbol, self.recovery_id
        ))
    }

    async fn perform(&self, ctx: &WrappedEquityRecoveryCtx) -> Result<Self::Output, Self::Error> {
        let symbol = self.symbol.clone();

        // Two-path claim: this job handles a positive `BaseWalletWrapped`
        // balance, which can be either an orphan (absent guard) or the
        // landed-but-unconfirmed `WrapSubmitted` outcome -- the wrap tx actually
        // landed so the tokens are WRAPPED, but the confirmation read failed and
        // the transfer job handed the slot to recovery as `HeldForRecovery`.
        // Claiming `HeldForRecovery` here is what drains that slot. The atomic
        // claim makes a concurrent `UnwrappedEquityRecovery` claim safe -- only
        // one wins, the other reschedules. Returns None only for `ActiveTransfer`
        // (a live transfer job owns the slot).
        let Some(guard) = claim_guard_for_recovery_or_orphan(&ctx.equity_in_progress, &symbol)
        else {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Rescheduling wrapped equity recovery: equity_in_progress held by \
                 active transfer; deferring",
            );
            ctx.queue
                .clone()
                .push_with_delay(self.clone(), ctx.reschedule_interval)
                .await?;
            return Ok(());
        };

        let current_state = ctx.store.load(&self.recovery_id).await?;

        if let Some(state) = &current_state
            && state.is_terminal()
        {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Skipping wrapped equity recovery: aggregate already terminal",
            );
            guard.release();
            return Ok(());
        }

        let result = match current_state {
            None => start_from_detect(ctx, &self.recovery_id, &symbol).await,
            Some(WrappedEquityRecovery::Detected { shares, .. }) => {
                resume_from_detected(ctx, &self.recovery_id, &symbol, shares).await
            }
            Some(WrappedEquityRecovery::OrphanDepositSubmitted {
                vault_deposit_tx_hash,
                ..
            }) => resume_from_confirm_deposit(ctx, &self.recovery_id, vault_deposit_tx_hash).await,
            // Terminal states are short-circuited by the `is_terminal` early
            // return above; enumerated explicitly (not `_`) so a new non-terminal
            // state fails to compile until it is wired into a resume path.
            Some(
                WrappedEquityRecovery::DispatchedToMint { .. }
                | WrappedEquityRecovery::DispatchedToRedemption { .. }
                | WrappedEquityRecovery::OrphanDeposited { .. }
                | WrappedEquityRecovery::Failed { .. },
            ) => Ok(()),
        };

        // - Ok: release the guard (removes the slot); recovery is done.
        // - NoBalanceSkip: map to Ok so apalis does NOT retry; the guard drops to
        //   its origin. A HeldForRecovery-origin skip self-reschedules since the
        //   reactor only re-dispatches on a positive balance.
        // - other Err: propagate; the guard drops, restoring its prior state.
        match result {
            Ok(()) => {
                guard.release();
                Ok(())
            }
            Err(WrappedEquityRecoveryJobError::NoBalanceSkip { symbol: ref sym }) => {
                if guard.claimed_from_held_for_recovery() {
                    debug!(
                        target: "rebalance",
                        symbol = %sym,
                        recovery_id = %self.recovery_id,
                        "Rescheduling wrapped equity recovery: no positive balance yet but slot \
                         is HeldForRecovery; re-enqueueing with delay to keep polling until the \
                         balance resolves or the slot is cleared",
                    );
                    ctx.queue
                        .clone()
                        .push_with_delay(self.clone(), ctx.reschedule_interval)
                        .await?;
                } else {
                    debug!(
                        target: "rebalance",
                        symbol = %sym,
                        recovery_id = %self.recovery_id,
                        "Skipping wrapped equity recovery: no positive balance in inventory view; \
                         orphan claim, guard drop removes entry so future inventory polls can \
                         re-trigger recovery",
                    );
                }
                Ok(())
            }
            Err(other) => Err(other),
        }
    }
}

/// Fresh recovery: read inventory, validate active-aggregate quantity, send
/// `Detect`, then dispatch from `Detected`.
async fn start_from_detect(
    ctx: &WrappedEquityRecoveryCtx,
    recovery_id: &WrappedEquityRecoveryId,
    symbol: &Symbol,
) -> Result<(), WrappedEquityRecoveryJobError> {
    let Some(snapshot) = read_recovery_snapshot(&ctx.inventory, symbol).await else {
        debug!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            "Skipping wrapped equity recovery: no positive balance in inventory view",
        );
        return Err(WrappedEquityRecoveryJobError::NoBalanceSkip {
            symbol: symbol.clone(),
        });
    };

    validate_active_aggregate_quantity(ctx, symbol, &snapshot).await?;

    ctx.store
        .send(
            recovery_id,
            WrappedEquityRecoveryCommand::Detect {
                symbol: symbol.clone(),
                shares: snapshot.shares,
            },
        )
        .await?;

    info!(
        target: "rebalance",
        %symbol,
        %recovery_id,
        shares = %snapshot.shares,
        ?snapshot.dispatch,
        "Wrapped equity recovery: dispatched detection",
    );

    dispatch_from_detected(ctx, recovery_id, symbol, snapshot.shares, snapshot.dispatch).await
}

/// Resume from `Detected`: a previous attempt persisted `Detect` but crashed
/// before any dispatch command landed. Re-read inventory and dispatch, failing
/// the stale aggregate if the balance vanished or its share count changed.
async fn resume_from_detected(
    ctx: &WrappedEquityRecoveryCtx,
    recovery_id: &WrappedEquityRecoveryId,
    symbol: &Symbol,
    detected_shares: FractionalShares,
) -> Result<(), WrappedEquityRecoveryJobError> {
    let Some(snapshot) = read_recovery_snapshot(&ctx.inventory, symbol).await else {
        warn!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            "Resuming wrapped recovery from Detected but inventory now reports zero balance; \
             failing the aggregate to free the symbol",
        );
        return fail_recovery(
            ctx,
            recovery_id,
            "inventory reports zero wrapped balance on resume from Detected".to_string(),
        )
        .await;
    };

    if snapshot.shares != detected_shares {
        warn!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            snapshot_shares = %snapshot.shares,
            %detected_shares,
            "Resuming wrapped recovery from Detected but inventory shares changed; \
             failing the stale aggregate to allow a fresh recovery",
        );
        return fail_recovery(
            ctx,
            recovery_id,
            format!(
                "inventory shares changed on resume from Detected: detected {detected_shares}, \
                 current {}",
                snapshot.shares
            ),
        )
        .await;
    }

    // Re-validate against the fresh snapshot: a crash can land here after the
    // inventory shifted, so do not trust the persisted `Detected` premise.
    if let Err(error) = validate_active_aggregate_quantity(ctx, symbol, &snapshot).await {
        if !is_business_validation_error(&error) {
            return Err(error);
        }

        warn!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            %error,
            "Wrapped equity recovery: active aggregate quantity mismatch on resume; \
             failing recovery",
        );
        return fail_recovery(
            ctx,
            recovery_id,
            format!("active aggregate validation failed on resume: {error}"),
        )
        .await;
    }

    dispatch_from_detected(ctx, recovery_id, symbol, snapshot.shares, snapshot.dispatch).await
}

/// Performs the dispatch step's I/O and records the outcome. For active
/// mint/redemption, resumes the transfer and records the dispatch (or
/// `RecoveryFailed`); for the orphan path, deposits the already-wrapped tokens;
/// for conflict, fails the aggregate.
async fn dispatch_from_detected(
    ctx: &WrappedEquityRecoveryCtx,
    recovery_id: &WrappedEquityRecoveryId,
    symbol: &Symbol,
    shares: FractionalShares,
    dispatch: DispatchDecision,
) -> Result<(), WrappedEquityRecoveryJobError> {
    match dispatch {
        DispatchDecision::ActiveMint(mint_id) => {
            match ctx.services.transfer.resume_mint(&mint_id).await {
                Ok(()) => {
                    info!(target: "rebalance", %mint_id, "Wrapped equity recovery: resume_mint succeeded");
                    ctx.store
                        .send(
                            recovery_id,
                            WrappedEquityRecoveryCommand::DispatchToMint { mint_id },
                        )
                        .await?;
                    Ok(())
                }
                Err(error) => {
                    warn!(target: "rebalance", %mint_id, ?error, "Wrapped equity recovery: resume_mint failed");
                    fail_recovery(ctx, recovery_id, format!("resume_mint failed: {error}")).await
                }
            }
        }
        DispatchDecision::ActiveRedemption(redemption_id) => {
            match ctx
                .services
                .transfer
                .resume_redemption(&redemption_id)
                .await
            {
                Ok(()) => {
                    info!(target: "rebalance", %redemption_id, "Wrapped equity recovery: resume_redemption succeeded");
                    ctx.store
                        .send(
                            recovery_id,
                            WrappedEquityRecoveryCommand::DispatchToRedemption { redemption_id },
                        )
                        .await?;
                    Ok(())
                }
                Err(error) => {
                    warn!(target: "rebalance", %redemption_id, ?error, "Wrapped equity recovery: resume_redemption failed");
                    fail_recovery(
                        ctx,
                        recovery_id,
                        format!("resume_redemption failed: {error}"),
                    )
                    .await
                }
            }
        }
        DispatchDecision::Orphan => {
            resume_from_submit_deposit(ctx, recovery_id, symbol, shares).await
        }
        DispatchDecision::Conflict {
            mint_id,
            redemption_id,
        } => {
            let reason = format!(
                "InventoryView reports active mint {mint_id} and active redemption \
                 {redemption_id} for symbol {symbol}; refusing to dispatch"
            );
            warn!(target: "rebalance", %symbol, %mint_id, %redemption_id, "Wrapped equity recovery: conflict");
            fail_recovery(ctx, recovery_id, reason).await
        }
    }
}

/// Orphan path step 1: resolve the wrapped token + vault, submit the deposit,
/// record the tx hash, then chain to confirm. The tokens are already wrapped
/// (wtSTOCK in the wallet), so there is no wrap step.
async fn resume_from_submit_deposit(
    ctx: &WrappedEquityRecoveryCtx,
    recovery_id: &WrappedEquityRecoveryId,
    symbol: &Symbol,
    shares: FractionalShares,
) -> Result<(), WrappedEquityRecoveryJobError> {
    let wrapped_token = match ctx.services.wrapper.lookup_derivative(symbol) {
        Ok(token) => token,
        Err(error) => {
            warn!(target: "rebalance", %symbol, ?error, "Wrapped equity recovery: lookup_derivative failed");
            return fail_recovery(
                ctx,
                recovery_id,
                format!("wrapper.lookup_derivative failed: {error}"),
            )
            .await;
        }
    };

    let vault_id = match ctx
        .services
        .vault_lookup
        .vault_id_for_token(wrapped_token)
        .await
    {
        Ok(id) => id,
        Err(error) => {
            warn!(target: "rebalance", %symbol, ?error, "Wrapped equity recovery: vault_id_for_token failed");
            return fail_recovery(
                ctx,
                recovery_id,
                format!("vault_lookup.vault_id_for_token failed: {error}"),
            )
            .await;
        }
    };

    let raw = match shares.to_u256_18_decimals() {
        Ok(raw) => raw,
        Err(error) => {
            warn!(target: "rebalance", %symbol, ?error, "Wrapped equity recovery: shares conversion failed");
            return fail_recovery(
                ctx,
                recovery_id,
                format!("shares conversion failed: {error}"),
            )
            .await;
        }
    };

    match ctx
        .services
        .raindex
        .submit_deposit(wrapped_token, vault_id, raw, TOKENIZED_EQUITY_DECIMALS)
        .await
    {
        Ok(vault_deposit_tx_hash) => {
            info!(target: "rebalance", %symbol, %vault_deposit_tx_hash, "Wrapped equity recovery: submit_deposit succeeded");
            ctx.store
                .send(
                    recovery_id,
                    WrappedEquityRecoveryCommand::SubmitOrphanDeposit {
                        vault_deposit_tx_hash,
                    },
                )
                .await?;
            resume_from_confirm_deposit(ctx, recovery_id, vault_deposit_tx_hash).await
        }
        Err(error) => {
            warn!(target: "rebalance", %symbol, ?error, "Wrapped equity recovery: submit_deposit failed");
            fail_recovery(
                ctx,
                recovery_id,
                format!("raindex.submit_deposit failed: {error}"),
            )
            .await
        }
    }
}

/// Orphan path step 2: confirm the Raindex deposit and record it. A dropped tx
/// is terminal; any other confirmation error is retryable so apalis re-runs from
/// the persisted `OrphanDepositSubmitted` without re-depositing.
async fn resume_from_confirm_deposit(
    ctx: &WrappedEquityRecoveryCtx,
    recovery_id: &WrappedEquityRecoveryId,
    vault_deposit_tx_hash: TxHash,
) -> Result<(), WrappedEquityRecoveryJobError> {
    match ctx.services.raindex.confirm_tx(vault_deposit_tx_hash).await {
        Ok(()) => {
            info!(target: "rebalance", %vault_deposit_tx_hash, "Wrapped equity recovery: confirm_tx succeeded");
            ctx.store
                .send(
                    recovery_id,
                    WrappedEquityRecoveryCommand::ConfirmOrphanDeposit,
                )
                .await
                .map_err(Into::into)
        }
        Err(error) => {
            warn!(target: "rebalance", %vault_deposit_tx_hash, ?error, "Wrapped equity recovery: confirm_tx failed");
            if error.is_transaction_dropped() {
                return fail_recovery(
                    ctx,
                    recovery_id,
                    format!("raindex.confirm_tx failed: {error}"),
                )
                .await;
            }
            Err(
                WrappedEquityRecoveryJobError::RetryableDepositConfirmation {
                    vault_deposit_tx_hash,
                },
            )
        }
    }
}

/// Records a terminal recovery failure as a `RecoveryFailed` event. Returns
/// `Ok(())` so the caller stops the chain without burning an apalis retry on an
/// already-terminal aggregate.
async fn fail_recovery(
    ctx: &WrappedEquityRecoveryCtx,
    recovery_id: &WrappedEquityRecoveryId,
    reason: String,
) -> Result<(), WrappedEquityRecoveryJobError> {
    ctx.store
        .send(
            recovery_id,
            WrappedEquityRecoveryCommand::FailRecovery { reason },
        )
        .await?;
    Ok(())
}

/// Distinguishes stale-premise business-validation failures (the active
/// mint/redemption no longer matches the wallet snapshot) from infrastructure
/// errors. On resume, the former terminalize the aggregate; the latter retry.
fn is_business_validation_error(error: &WrappedEquityRecoveryJobError) -> bool {
    match error {
        WrappedEquityRecoveryJobError::ActiveMintQuantityMismatch { .. }
        | WrappedEquityRecoveryJobError::ActiveRedemptionQuantityMismatch { .. }
        | WrappedEquityRecoveryJobError::ActiveMintMissing { .. }
        | WrappedEquityRecoveryJobError::ActiveRedemptionMissing { .. } => true,
        WrappedEquityRecoveryJobError::Aggregate(_)
        | WrappedEquityRecoveryJobError::Domain(_)
        | WrappedEquityRecoveryJobError::ActiveMintAggregate(_)
        | WrappedEquityRecoveryJobError::ActiveRedemptionAggregate(_)
        | WrappedEquityRecoveryJobError::Reschedule(_)
        | WrappedEquityRecoveryJobError::RetryableDepositConfirmation { .. }
        | WrappedEquityRecoveryJobError::NoBalanceSkip { .. } => false,
    }
}

struct RecoverySnapshot {
    shares: st0x_execution::FractionalShares,
    dispatch: DispatchDecision,
}

#[derive(Debug)]
enum DispatchDecision {
    ActiveMint(IssuerRequestId),
    ActiveRedemption(RedemptionAggregateId),
    Orphan,
    /// `InventoryView` reports both an active mint and an active redemption
    /// for the same symbol. A symbol can only be in one in-flight transfer
    /// at a time -- this is a corrupt-state signal, not a normal dispatch
    /// path.
    Conflict {
        mint_id: IssuerRequestId,
        redemption_id: RedemptionAggregateId,
    },
}

async fn read_recovery_snapshot(
    inventory: &BroadcastingInventory,
    symbol: &Symbol,
) -> Option<RecoverySnapshot> {
    let view = inventory.read().await;
    let shares = view.inflight_equity_at(symbol, InFlightEquityLocation::BaseWalletWrapped)?;
    if shares == st0x_execution::FractionalShares::ZERO {
        return None;
    }
    let dispatch = decide_dispatch(&view, symbol);
    drop(view);
    Some(RecoverySnapshot { shares, dispatch })
}

/// Confirms the active mint or redemption aggregate carries the same quantity
/// as the wrapped wallet snapshot. Without this check, the recovery stream
/// would record `snapshot.shares` for an aggregate that was actually set up
/// for a different amount, leaving the audit trail and the resumed work
/// disagreeing on how many shares moved.
async fn validate_active_aggregate_quantity(
    ctx: &WrappedEquityRecoveryCtx,
    symbol: &Symbol,
    snapshot: &RecoverySnapshot,
) -> Result<(), WrappedEquityRecoveryJobError> {
    match &snapshot.dispatch {
        DispatchDecision::ActiveMint(mint_id) => {
            let mint = ctx.mint_store.load(mint_id).await?.ok_or_else(|| {
                WrappedEquityRecoveryJobError::ActiveMintMissing {
                    symbol: symbol.clone(),
                    mint_id: mint_id.clone(),
                }
            })?;
            let aggregate_shares = FractionalShares::new(mint.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(WrappedEquityRecoveryJobError::ActiveMintQuantityMismatch {
                    symbol: symbol.clone(),
                    mint_id: mint_id.clone(),
                    snapshot_shares: snapshot.shares,
                    aggregate_shares,
                });
            }
            Ok(())
        }
        DispatchDecision::ActiveRedemption(redemption_id) => {
            let redemption = ctx
                .redemption_store
                .load(redemption_id)
                .await?
                .ok_or_else(|| WrappedEquityRecoveryJobError::ActiveRedemptionMissing {
                    symbol: symbol.clone(),
                    redemption_id: redemption_id.clone(),
                })?;
            let aggregate_shares = FractionalShares::new(redemption.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(
                    WrappedEquityRecoveryJobError::ActiveRedemptionQuantityMismatch {
                        symbol: symbol.clone(),
                        redemption_id: redemption_id.clone(),
                        snapshot_shares: snapshot.shares,
                        aggregate_shares,
                    },
                );
            }
            Ok(())
        }
        DispatchDecision::Orphan | DispatchDecision::Conflict { .. } => Ok(()),
    }
}

fn decide_dispatch(view: &InventoryView, symbol: &Symbol) -> DispatchDecision {
    match (view.active_mint(symbol), view.active_redemption(symbol)) {
        (Some(mint_id), Some(redemption_id)) => DispatchDecision::Conflict {
            mint_id: mint_id.clone(),
            redemption_id: redemption_id.clone(),
        },
        (Some(mint_id), None) => DispatchDecision::ActiveMint(mint_id.clone()),
        (None, Some(redemption_id)) => DispatchDecision::ActiveRedemption(redemption_id.clone()),
        (None, None) => DispatchDecision::Orphan,
    }
}

#[cfg(test)]
mod tests {
    use alloy::primitives::{Address, B256, U256};
    use chrono::Utc;
    use std::collections::BTreeMap;
    use std::sync::{Arc, RwLock};
    use tokio::sync::broadcast;
    use uuid::Uuid;

    use st0x_event_sorcery::test_store;
    use st0x_float_macro::float;
    use st0x_raindex::{Raindex, RaindexVaultId};
    use st0x_tokenization::mock::{MockCompletionOutcome, MockDetectionOutcome, MockTokenizer};
    use st0x_tokenization::{Tokenizer, issuer_request_id, tokenization_request_id};
    use st0x_wrapper::{MockWrapper, Wrapper};

    use super::super::aggregate::{
        WrappedEquityRecovery, WrappedEquityRecoveryCommand, WrappedEquityRecoveryServices,
    };
    use super::*;
    use crate::equity_redemption::{
        EquityRedemption, EquityRedemptionCommand, redemption_aggregate_id,
    };
    use crate::inventory::BroadcastingInventory;
    use crate::inventory::view::{InFlightEquityLocation, InventoryView};
    use crate::onchain::mock::{ConfirmTxBehavior, DepositBehavior, DepositCall, MockRaindex};
    use crate::rebalancing::equity::CrossVenueEquityTransfer;
    use crate::tokenized_equity_mint::TokenizedEquityMintCommand;
    use crate::vault_lookup::{MockVaultLookup, VaultLookup};

    #[tokio::test]
    async fn guard_contention_reschedules_without_dropping_the_recovery() {
        let symbol = Symbol::new("AAPL").unwrap();
        let equity_in_progress = Arc::new(RwLock::new(HashMap::from([(
            symbol.clone(),
            GuardState::ActiveTransfer { generation: 0 },
        )])));

        let (pool, apalis_pool) = crate::test_utils::setup_test_pools().await;

        let raindex: Arc<dyn Raindex> = Arc::new(MockRaindex::new());
        let vault_lookup: Arc<dyn VaultLookup> = Arc::new(MockVaultLookup::new());
        let wrapper: Arc<dyn Wrapper> = Arc::new(MockWrapper::new());
        let mint_store = Arc::new(test_store::<TokenizedEquityMint>(pool.clone(), ()));
        let redemption_store = Arc::new(test_store(pool.clone(), ()));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            raindex.clone(),
            vault_lookup.clone(),
            Arc::new(MockTokenizer::new()),
            wrapper.clone(),
            Address::random(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        let services = WrappedEquityRecoveryServices {
            raindex,
            vault_lookup,
            wrapper,
            transfer,
        };
        let store = Arc::new(test_store(pool.clone(), ()));

        let (sender, _receiver) = broadcast::channel(16);
        let inventory = Arc::new(BroadcastingInventory::new(InventoryView::default(), sender));
        let ctx = WrappedEquityRecoveryCtx {
            inventory,
            store,
            services,
            mint_store,
            redemption_store,
            equity_in_progress,
            queue: WrappedEquityRecoveryJobQueue::new(&apalis_pool),
            reschedule_interval: Duration::from_secs(1),
        };
        let job = WrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
        };

        job.perform(&ctx).await.unwrap();

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            state.is_none(),
            "guard-held perform() must not start recovery; aggregate should be absent, got {state:?}",
        );

        let (rescheduled,): (i64,) =
            sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<WrappedEquityRecoveryJob>())
                .fetch_one(ctx.queue.pool())
                .await
                .unwrap();
        assert_eq!(
            rescheduled, 1,
            "guard contention must reschedule the wrapped recovery job, not mark it done",
        );
    }

    #[tokio::test]
    async fn enqueue_dedup_matches_symbol_exactly_not_as_substring() {
        let apalis_pool = crate::test_utils::setup_test_apalis_pool().await;

        let mut queue = WrappedEquityRecoveryJobQueue::new(&apalis_pool);
        queue
            .push(WrappedEquityRecoveryJob {
                symbol: Symbol::new("GOOGL").unwrap(),
                recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
            })
            .await
            .unwrap();

        // The exact query the reactor uses to dedupe wrapped-recovery enqueues.
        const DEDUP_QUERY: &str = "SELECT COUNT(*) FROM Jobs \
             WHERE job_type = ? \
             AND status IN ('Pending', 'Queued', 'Running') \
             AND json_extract(job, '$.symbol') = ?";
        let job_type = std::any::type_name::<WrappedEquityRecoveryJob>();

        let (exact,): (i64,) = sqlx_apalis::query_as(DEDUP_QUERY)
            .bind(job_type)
            .bind("GOOGL")
            .fetch_one(&apalis_pool)
            .await
            .unwrap();
        assert_eq!(exact, 1, "exact symbol must match the queued GOOGL job");

        let (substring,): (i64,) = sqlx_apalis::query_as(DEDUP_QUERY)
            .bind(job_type)
            .bind("GOOG")
            .fetch_one(&apalis_pool)
            .await
            .unwrap();
        assert_eq!(
            substring, 0,
            "a substring ticker (GOOG) must not match the queued GOOGL job",
        );
    }

    fn aapl() -> Symbol {
        Symbol::new("AAPL").unwrap()
    }

    fn five_shares() -> FractionalShares {
        FractionalShares::new(float!(5))
    }

    fn mock_vault_lookup() -> MockVaultLookup {
        MockVaultLookup::new()
            .with_vault(Address::ZERO, RaindexVaultId(B256::ZERO))
            .with_default_vault(RaindexVaultId(B256::ZERO))
    }

    /// Builds a recovery ctx with the aggregate store pure (`()` services) and
    /// the onchain services on the ctx, mirroring production wiring. Failure-path
    /// tests inject reverting/failing mocks while the rest stays succeeding.
    async fn test_ctx_with_services(
        view: InventoryView,
        equity_in_progress: HashMap<Symbol, GuardState>,
        raindex: Arc<dyn Raindex>,
        wrapper: Arc<dyn Wrapper>,
        vault_lookup: Arc<dyn VaultLookup>,
        tokenizer: Arc<dyn Tokenizer>,
    ) -> WrappedEquityRecoveryCtx {
        let (pool, apalis_pool) = crate::test_utils::setup_test_pools().await;

        let mint_store = Arc::new(test_store::<TokenizedEquityMint>(pool.clone(), ()));
        let redemption_store = Arc::new(test_store(pool.clone(), ()));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            raindex.clone(),
            vault_lookup.clone(),
            tokenizer,
            wrapper.clone(),
            Address::random(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        let services = WrappedEquityRecoveryServices {
            raindex,
            vault_lookup,
            wrapper,
            transfer,
        };
        let store = Arc::new(test_store(pool, ()));
        let (sender, _receiver) = broadcast::channel(16);
        let inventory = Arc::new(BroadcastingInventory::new(view, sender));

        WrappedEquityRecoveryCtx {
            inventory,
            store,
            services,
            mint_store,
            redemption_store,
            equity_in_progress: Arc::new(RwLock::new(equity_in_progress)),
            queue: WrappedEquityRecoveryJobQueue::new(&apalis_pool),
            reschedule_interval: Duration::from_secs(1),
        }
    }

    /// `test_ctx_with_services` with succeeding raindex/wrapper/vault mocks and a
    /// caller-supplied tokenizer, for tests whose resumed redemption must drive
    /// detection/completion polling to a terminal outcome.
    async fn test_ctx_with_tokenizer(
        view: InventoryView,
        equity_in_progress: HashMap<Symbol, GuardState>,
        tokenizer: Arc<dyn Tokenizer>,
    ) -> WrappedEquityRecoveryCtx {
        test_ctx_with_services(
            view,
            equity_in_progress,
            Arc::new(MockRaindex::new()),
            Arc::new(MockWrapper::new()),
            Arc::new(mock_vault_lookup()),
            tokenizer,
        )
        .await
    }

    /// `test_ctx_with_services` with every dependency backed by a succeeding mock.
    async fn test_ctx(
        view: InventoryView,
        equity_in_progress: HashMap<Symbol, GuardState>,
    ) -> WrappedEquityRecoveryCtx {
        test_ctx_with_tokenizer(view, equity_in_progress, Arc::new(MockTokenizer::new())).await
    }

    /// Seeds a `Detected` aggregate and returns its id.
    async fn seed_detected(ctx: &WrappedEquityRecoveryCtx) -> WrappedEquityRecoveryId {
        let recovery_id = WrappedEquityRecoveryId(Uuid::new_v4());
        ctx.store
            .send(
                &recovery_id,
                WrappedEquityRecoveryCommand::Detect {
                    symbol: aapl(),
                    shares: five_shares(),
                },
            )
            .await
            .unwrap();
        recovery_id
    }

    /// Seeds an `OrphanDepositSubmitted` aggregate (the confirm step's entry
    /// state) carrying `deposit_tx`.
    async fn seed_orphan_deposit_submitted(
        ctx: &WrappedEquityRecoveryCtx,
        deposit_tx: TxHash,
    ) -> WrappedEquityRecoveryId {
        let recovery_id = seed_detected(ctx).await;
        ctx.store
            .send(
                &recovery_id,
                WrappedEquityRecoveryCommand::SubmitOrphanDeposit {
                    vault_deposit_tx_hash: deposit_tx,
                },
            )
            .await
            .unwrap();
        recovery_id
    }

    async fn assert_failed_with(
        ctx: &WrappedEquityRecoveryCtx,
        recovery_id: &WrappedEquityRecoveryId,
        reason_fragment: &str,
    ) {
        let state = ctx.store.load(recovery_id).await.unwrap();
        let Some(WrappedEquityRecovery::Failed { reason, .. }) = state else {
            panic!("expected Failed state, got {state:?}");
        };
        assert!(
            reason.contains(reason_fragment),
            "RecoveryFailed reason should mention {reason_fragment:?}; got {reason:?}",
        );
    }

    /// A retry that finds the aggregate already in `OrphanDepositSubmitted` must
    /// confirm the persisted deposit tx, never submit a second deposit.
    #[tokio::test]
    async fn perform_resumes_from_orphan_deposit_submitted_without_redepositing() {
        let symbol = aapl();
        let raindex = Arc::new(MockRaindex::new());
        let ctx = test_ctx_with_services(
            InventoryView::default(),
            HashMap::new(),
            raindex.clone(),
            Arc::new(MockWrapper::new()),
            Arc::new(mock_vault_lookup()),
            Arc::new(MockTokenizer::new()),
        )
        .await;
        let deposit_tx = TxHash::from([0x22; 32]);
        let recovery_id = seed_orphan_deposit_submitted(&ctx, deposit_tx).await;

        let job = WrappedEquityRecoveryJob {
            symbol,
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("resume from OrphanDepositSubmitted should run to completion");

        let state = ctx.store.load(&recovery_id).await.unwrap();
        let Some(WrappedEquityRecovery::OrphanDeposited {
            vault_deposit_tx_hash,
            ..
        }) = state
        else {
            panic!("resume must complete the orphan path, got {state:?}");
        };
        assert_eq!(
            vault_deposit_tx_hash, deposit_tx,
            "the resumed run must confirm the persisted deposit tx, not submit a second deposit",
        );
        assert_eq!(
            raindex.last_deposit_call(),
            None,
            "resuming from OrphanDepositSubmitted must not call submit_deposit again",
        );
    }

    /// The orphan deposit must use the resolved wrapped token at tokenized-equity
    /// precision (18 decimals), the standard wtSTOCK is minted at.
    #[tokio::test]
    async fn submit_orphan_deposit_uses_wrapped_token_at_tokenized_precision() {
        let wrapped_token = Address::random();
        let raindex = Arc::new(MockRaindex::new());
        let ctx = test_ctx_with_services(
            InventoryView::default(),
            HashMap::new(),
            raindex.clone(),
            Arc::new(MockWrapper::new().with_wrapped_token(wrapped_token)),
            Arc::new(mock_vault_lookup()),
            Arc::new(MockTokenizer::new()),
        )
        .await;
        let recovery_id = seed_detected(&ctx).await;

        resume_from_submit_deposit(&ctx, &recovery_id, &aapl(), five_shares())
            .await
            .expect("deposit should succeed");

        assert_eq!(
            raindex.last_deposit_call(),
            Some(DepositCall {
                token: wrapped_token,
                vault_id: RaindexVaultId(B256::ZERO),
                amount: five_shares().to_u256_18_decimals().unwrap(),
                decimals: TOKENIZED_EQUITY_DECIMALS,
            }),
            "the deposit must use the resolved wrapped token at tokenized-equity precision",
        );
    }

    #[tokio::test]
    async fn submit_deposit_revert_records_recovery_failed() {
        let ctx = test_ctx_with_services(
            InventoryView::default(),
            HashMap::new(),
            Arc::new(
                MockRaindex::new().with_deposit_behavior(DepositBehavior::FailExecutionReverted),
            ),
            Arc::new(MockWrapper::new()),
            Arc::new(mock_vault_lookup()),
            Arc::new(MockTokenizer::new()),
        )
        .await;
        let recovery_id = seed_detected(&ctx).await;

        resume_from_submit_deposit(&ctx, &recovery_id, &aapl(), five_shares())
            .await
            .expect("a reverted deposit is recorded, not surfaced as a job error");

        assert_failed_with(&ctx, &recovery_id, "submit_deposit failed").await;
    }

    #[tokio::test]
    async fn submit_deposit_vault_lookup_failure_records_recovery_failed() {
        let ctx = test_ctx_with_services(
            InventoryView::default(),
            HashMap::new(),
            Arc::new(MockRaindex::new()),
            Arc::new(MockWrapper::new().with_wrapped_token(Address::random())),
            // Empty vault lookup -> `vault_id_for_token` fails.
            Arc::new(MockVaultLookup::new()),
            Arc::new(MockTokenizer::new()),
        )
        .await;
        let recovery_id = seed_detected(&ctx).await;

        resume_from_submit_deposit(&ctx, &recovery_id, &aapl(), five_shares())
            .await
            .expect("a vault lookup failure is recorded, not surfaced as a job error");

        assert_failed_with(&ctx, &recovery_id, "vault_id_for_token failed").await;
    }

    #[tokio::test]
    async fn submit_deposit_wrapper_lookup_failure_records_recovery_failed() {
        let ctx = test_ctx_with_services(
            InventoryView::default(),
            HashMap::new(),
            Arc::new(MockRaindex::new()),
            // `lookup_derivative` fails before the vault lookup / deposit run.
            Arc::new(MockWrapper::failing_derivative_lookup()),
            Arc::new(mock_vault_lookup()),
            Arc::new(MockTokenizer::new()),
        )
        .await;
        let recovery_id = seed_detected(&ctx).await;

        resume_from_submit_deposit(&ctx, &recovery_id, &aapl(), five_shares())
            .await
            .expect("a wrapper lookup failure is recorded, not surfaced as a job error");

        assert_failed_with(&ctx, &recovery_id, "wrapper.lookup_derivative failed").await;
    }

    /// A dropped deposit tx is terminal: recorded as `RecoveryFailed`.
    #[tokio::test]
    async fn confirm_deposit_dropped_tx_records_recovery_failed() {
        let deposit_tx = TxHash::from([0x22; 32]);
        let ctx = test_ctx_with_services(
            InventoryView::default(),
            HashMap::new(),
            Arc::new(MockRaindex::new().with_confirm_behavior(ConfirmTxBehavior::Fail)),
            Arc::new(MockWrapper::new()),
            Arc::new(mock_vault_lookup()),
            Arc::new(MockTokenizer::new()),
        )
        .await;
        let recovery_id = seed_orphan_deposit_submitted(&ctx, deposit_tx).await;

        resume_from_confirm_deposit(&ctx, &recovery_id, deposit_tx)
            .await
            .expect("a dropped deposit tx is recorded, not surfaced as a job error");

        assert_failed_with(&ctx, &recovery_id, "confirm_tx failed").await;
    }

    /// A transient (non-dropped) confirmation failure surfaces as a job error so
    /// apalis retries from the persisted `OrphanDepositSubmitted`, never
    /// re-depositing.
    #[tokio::test]
    async fn confirm_deposit_retryable_error_propagates_against_persisted_tx() {
        let deposit_tx = TxHash::from([0x22; 32]);
        let raindex =
            Arc::new(MockRaindex::new().with_confirm_behavior(ConfirmTxBehavior::Retryable));
        let ctx = test_ctx_with_services(
            InventoryView::default(),
            HashMap::new(),
            raindex.clone(),
            Arc::new(MockWrapper::new()),
            Arc::new(mock_vault_lookup()),
            Arc::new(MockTokenizer::new()),
        )
        .await;
        let recovery_id = seed_orphan_deposit_submitted(&ctx, deposit_tx).await;

        let error = resume_from_confirm_deposit(&ctx, &recovery_id, deposit_tx)
            .await
            .expect_err("a retryable confirmation must surface as a job error so apalis retries");

        assert!(matches!(
            error,
            WrappedEquityRecoveryJobError::RetryableDepositConfirmation { .. }
        ));
        assert_eq!(
            raindex.last_confirmed_tx(),
            Some(deposit_tx),
            "the confirm step must confirm the persisted deposit tx hash",
        );
    }

    #[tokio::test]
    async fn dispatch_resume_mint_failure_records_recovery_failed() {
        let ctx = test_ctx(InventoryView::default(), HashMap::new()).await;
        let recovery_id = seed_detected(&ctx).await;

        // No mint aggregate exists, so `resume_mint` fails.
        dispatch_from_detected(
            &ctx,
            &recovery_id,
            &aapl(),
            five_shares(),
            DispatchDecision::ActiveMint(issuer_request_id("ISS-NONEXISTENT")),
        )
        .await
        .expect("a failed mint resume is recorded, not surfaced as a job error");

        assert_failed_with(&ctx, &recovery_id, "resume_mint failed").await;
    }

    #[tokio::test]
    async fn dispatch_resume_redemption_failure_records_recovery_failed() {
        let ctx = test_ctx(InventoryView::default(), HashMap::new()).await;
        let recovery_id = seed_detected(&ctx).await;

        dispatch_from_detected(
            &ctx,
            &recovery_id,
            &aapl(),
            five_shares(),
            DispatchDecision::ActiveRedemption(redemption_aggregate_id("nonexistent")),
        )
        .await
        .expect("a failed redemption resume is recorded, not surfaced as a job error");

        assert_failed_with(&ctx, &recovery_id, "resume_redemption failed").await;
    }

    /// A retry that finds the aggregate already terminal must skip without
    /// emitting new events.
    #[tokio::test]
    async fn perform_skips_already_terminal_aggregate() {
        let symbol = aapl();
        let ctx = test_ctx(InventoryView::default(), HashMap::new()).await;
        let recovery_id = seed_detected(&ctx).await;
        ctx.store
            .send(
                &recovery_id,
                WrappedEquityRecoveryCommand::FailRecovery {
                    reason: "already done".to_string(),
                },
            )
            .await
            .unwrap();

        let job = WrappedEquityRecoveryJob {
            symbol,
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("terminal aggregate is skipped");

        assert_failed_with(&ctx, &recovery_id, "already done").await;
    }

    fn view_with_wrapped_balance(symbol: &Symbol, shares: FractionalShares) -> InventoryView {
        let mut balances = BTreeMap::new();
        balances.insert(symbol.clone(), shares);
        let now = Utc::now();
        InventoryView::default().set_inflight_equity_at_location(
            InFlightEquityLocation::BaseWalletWrapped,
            &balances,
            now,
            now,
        )
    }

    /// Resuming from `Detected` after the wrapped balance vanished must fail the
    /// aggregate so the symbol is freed for a fresh recovery.
    #[tokio::test]
    async fn perform_resume_from_detected_with_zero_balance_fails_aggregate() {
        let symbol = aapl();
        let ctx = test_ctx(InventoryView::default(), HashMap::new()).await;
        let recovery_id = seed_detected(&ctx).await;

        let job = WrappedEquityRecoveryJob {
            symbol,
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("resume from Detected with no balance fails the aggregate, not the job");

        assert_failed_with(&ctx, &recovery_id, "zero wrapped balance").await;
    }

    /// Resuming from `Detected` when the inventory share count changed must fail
    /// the stale aggregate rather than dispatch against a mismatched amount.
    #[tokio::test]
    async fn perform_resume_from_detected_with_changed_shares_fails_stale_aggregate() {
        let symbol = aapl();
        // The seeded `Detected` carries five_shares; inventory now reports seven.
        let ctx = test_ctx(
            view_with_wrapped_balance(&symbol, FractionalShares::new(float!(7))),
            HashMap::new(),
        )
        .await;
        let recovery_id = seed_detected(&ctx).await;

        let job = WrappedEquityRecoveryJob {
            symbol,
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("resume from Detected with changed shares fails the stale aggregate");

        assert_failed_with(&ctx, &recovery_id, "shares changed").await;
    }

    /// Resuming from `Detected` when the active mint's quantity no longer matches
    /// the detected shares is a terminal business-validation failure, not a
    /// retryable one: the stale aggregate must fail (freeing the guard), never
    /// wedge in `Detected`.
    #[tokio::test]
    async fn perform_resume_from_detected_with_quantity_mismatch_fails_stale_aggregate() {
        let symbol = aapl();
        let mint_id = issuer_request_id("ISS001");
        // Inventory reports an active mint for the detected five shares...
        let view = view_with_wrapped_balance(&symbol, five_shares())
            .set_active_mint(symbol.clone(), mint_id.clone());
        let ctx = test_ctx(view, HashMap::new()).await;
        let recovery_id = seed_detected(&ctx).await;

        // ...but the mint aggregate carries a different quantity (3 != 5).
        ctx.mint_store
            .send(
                &mint_id,
                TokenizedEquityMintCommand::RecordMintRequested {
                    issuer_request_id: mint_id.clone(),
                    symbol: symbol.clone(),
                    quantity: float!(3),
                    wallet: Address::random(),
                    tokenization_request_id: tokenization_request_id("tok-req-mismatch"),
                },
            )
            .await
            .unwrap();

        let job = WrappedEquityRecoveryJob {
            symbol,
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("a quantity mismatch fails the stale aggregate, not the job");

        assert_failed_with(&ctx, &recovery_id, "active aggregate validation").await;
    }

    /// An orphan-origin (absent guard) no-balance skip must NOT self-reschedule:
    /// the slot drops to absent and the reactor re-triggers on the next
    /// positive-balance poll.
    #[tokio::test]
    async fn perform_skips_when_inventory_reports_no_balance() {
        let symbol = aapl();
        let ctx = test_ctx(InventoryView::default(), HashMap::new()).await;
        let job = WrappedEquityRecoveryJob {
            symbol,
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
        };

        job.perform(&ctx)
            .await
            .expect("a no-balance perform is a no-op");

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            state.is_none(),
            "no inventory balance must not start a recovery aggregate, got {state:?}",
        );

        let (rescheduled,): (i64,) =
            sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<WrappedEquityRecoveryJob>())
                .fetch_one(ctx.queue.pool())
                .await
                .unwrap();
        assert_eq!(
            rescheduled, 0,
            "an orphan no-balance skip must NOT reschedule; the reactor re-triggers on next poll",
        );
    }

    /// A `HeldForRecovery`-origin no-balance skip must restore the slot to
    /// `HeldForRecovery` AND self-reschedule with a delay -- the reactor only
    /// re-dispatches on a positive balance, so without the reschedule a slot
    /// whose tokens left the wallet out of band would wedge.
    #[tokio::test]
    async fn perform_no_balance_skip_restores_held_for_recovery_and_reschedules() {
        let symbol = aapl();
        let ctx = test_ctx(
            InventoryView::default(),
            HashMap::from([(symbol.clone(), GuardState::HeldForRecovery)]),
        )
        .await;
        let job = WrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
        };

        job.perform(&ctx)
            .await
            .expect("no-balance skip must return Ok");

        assert_eq!(
            ctx.equity_in_progress.read().unwrap().get(&symbol),
            Some(&GuardState::HeldForRecovery),
            "no-balance skip from HeldForRecovery claim must restore to HeldForRecovery",
        );

        let (rescheduled,): (i64,) =
            sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<WrappedEquityRecoveryJob>())
                .fetch_one(ctx.queue.pool())
                .await
                .unwrap();
        assert_eq!(
            rescheduled, 1,
            "a HeldForRecovery-origin no-balance skip must enqueue a delayed job to keep polling",
        );
    }

    /// Job-level routing: an active mint for the symbol resumes the mint and
    /// records `DispatchToMint` -- not the orphan deposit path.
    #[tokio::test]
    async fn perform_drives_active_mint_path_to_dispatched_to_mint() {
        let symbol = aapl();
        let mint_id = issuer_request_id("ISS001");
        let view = view_with_wrapped_balance(&symbol, five_shares())
            .set_active_mint(symbol.clone(), mint_id.clone());
        let ctx = test_ctx(view, HashMap::new()).await;

        // Seed the mint to `TokensWrapped` so `resume_mint` runs to completion
        // under the succeeding mocks.
        ctx.mint_store
            .send(
                &mint_id,
                TokenizedEquityMintCommand::RecordMintRequested {
                    issuer_request_id: mint_id.clone(),
                    symbol: symbol.clone(),
                    quantity: float!(5),
                    wallet: Address::random(),
                    tokenization_request_id: tokenization_request_id("tok-req-dispatch"),
                },
            )
            .await
            .unwrap();
        ctx.mint_store
            .send(
                &mint_id,
                TokenizedEquityMintCommand::RecordTokensReceived {
                    tx_hash: Some(TxHash::repeat_byte(0x11)),
                    token_symbol: Some(format!("t{symbol}")),
                    fees: None,
                },
            )
            .await
            .unwrap();
        let wrap_tx = TxHash::repeat_byte(0x22);
        ctx.mint_store
            .send(
                &mint_id,
                TokenizedEquityMintCommand::SubmitWrap {
                    wrap_tx_hash: wrap_tx,
                },
            )
            .await
            .unwrap();
        ctx.mint_store
            .send(
                &mint_id,
                TokenizedEquityMintCommand::WrapTokens {
                    wrap_tx_hash: wrap_tx,
                    wrapped_shares: U256::from(5_000_000_000_000_000_000u128),
                    wrap_block: 1,
                },
            )
            .await
            .unwrap();

        let job = WrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
        };
        job.perform(&ctx)
            .await
            .expect("active-mint recovery should run to completion");

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        let Some(WrappedEquityRecovery::DispatchedToMint {
            mint_id: dispatched,
            ..
        }) = state
        else {
            panic!("active mint must route to DispatchedToMint, got {state:?}");
        };
        assert_eq!(
            dispatched, mint_id,
            "the dispatched mint id must be the active mint from the inventory",
        );

        let mint = ctx.mint_store.load(&mint_id).await.unwrap();
        assert!(
            matches!(mint, Some(TokenizedEquityMint::DepositedIntoRaindex { .. })),
            "resume_mint must drive the seeded mint to completion, got {mint:?}",
        );
    }

    /// Job-level routing: an active redemption for the symbol resumes the
    /// redemption and records `DispatchToRedemption`.
    #[tokio::test]
    async fn perform_drives_active_redemption_path_to_dispatched_to_redemption() {
        let symbol = aapl();
        let redemption_id = redemption_aggregate_id("RED001");
        let view = view_with_wrapped_balance(&symbol, five_shares())
            .set_active_redemption(symbol.clone(), redemption_id.clone());
        let tokenizer = Arc::new(
            MockTokenizer::new()
                .with_detection_outcome(MockDetectionOutcome::Detected)
                .with_completion_outcome(MockCompletionOutcome::Completed),
        );
        let ctx = test_ctx_with_tokenizer(view, HashMap::new(), tokenizer).await;

        // Seed the redemption at `VaultWithdrawSubmitted`; `resume_redemption`
        // walks it to `Completed` under the detection/completion mocks.
        ctx.redemption_store
            .send(
                &redemption_id,
                EquityRedemptionCommand::Redeem {
                    symbol: symbol.clone(),
                    quantity: float!(5),
                    token: Address::random(),
                    amount: five_shares().to_u256_18_decimals().unwrap(),
                },
            )
            .await
            .unwrap();

        let job = WrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
        };
        job.perform(&ctx)
            .await
            .expect("active-redemption recovery should run to completion");

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        let Some(WrappedEquityRecovery::DispatchedToRedemption {
            redemption_id: dispatched,
            ..
        }) = state
        else {
            panic!("active redemption must route to DispatchedToRedemption, got {state:?}");
        };
        assert_eq!(
            dispatched, redemption_id,
            "the dispatched redemption id must be the active redemption from the inventory",
        );

        let redemption = ctx.redemption_store.load(&redemption_id).await.unwrap();
        assert!(
            matches!(redemption, Some(EquityRedemption::Completed { .. })),
            "resume_redemption must drive the seeded redemption to completion, got {redemption:?}",
        );
    }

    /// An inventory conflict (both an active mint and an active redemption for
    /// the symbol) terminalizes the aggregate as `Failed` and returns `Ok`
    /// (no apalis retry, guard released), never dispatching.
    #[tokio::test]
    async fn perform_conflict_fails_recovery_without_retrying() {
        let symbol = aapl();
        let mint_id = issuer_request_id("ISS001");
        let redemption_id = redemption_aggregate_id("RED001");
        let view = view_with_wrapped_balance(&symbol, five_shares())
            .set_active_mint(symbol.clone(), mint_id)
            .set_active_redemption(symbol.clone(), redemption_id);
        let ctx = test_ctx(view, HashMap::new()).await;
        let job = WrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
        };

        job.perform(&ctx)
            .await
            .expect("an inventory conflict should terminalize without retrying");

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            matches!(state, Some(WrappedEquityRecovery::Failed { .. })),
            "a conflict must terminalize the aggregate as Failed, got {state:?}",
        );
        assert!(
            !ctx.equity_in_progress.read().unwrap().contains_key(&symbol),
            "a conflict terminalisation must release the guard, leaving no in-progress slot",
        );
    }
}
