//! Apalis job that orchestrates wrapped-equity recovery.
//!
//! Enqueued per symbol with a positive `BaseWalletWrappedEquity` balance.
//! The job is a thin orchestrator: it reads `InventoryView`, picks a
//! dispatch path, and sends the command sequence through the aggregate's
//! store. All side effects (raindex deposit/confirm, mint/redemption
//! resume, wrapped-token lookup) live in the aggregate's command handlers
//! via its `Services`.
//!
//! Steps:
//!
//! 1. Claim the `equity_in_progress` guard for the symbol. If another task
//!    already holds it, the job reschedules itself with a delay so an
//!    unchanged wallet balance is not stranded waiting for another snapshot.
//! 2. Read the inventory view's wallet balance + active mint/redemption
//!    maps to pick a `DispatchDecision`.
//! 3. Send `Detect` followed by the path-specific command sequence:
//!    `DispatchToMint`, `DispatchToRedemption`, or `SubmitOrphanDeposit +
//!    ConfirmOrphanDeposit`. The aggregate's terminal state encodes the
//!    outcome; no separate completion command is needed.
//!
//! The job carries its `WrappedEquityRecoveryId` in the apalis payload
//! (generated by the reactor when pushing the job) so retries target the
//! same aggregate -- the next command in the sequence picks up wherever
//! the previous attempt stopped.

use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::sync::{Arc, RwLock};
use std::time::Duration;
use thiserror::Error;
use tracing::{debug, info, warn};

use st0x_event_sorcery::{SendError, Store};
use st0x_execution::{FractionalShares, Symbol};

use super::aggregate::{
    WrappedEquityRecovery, WrappedEquityRecoveryCommand, WrappedEquityRecoveryError,
    WrappedEquityRecoveryId,
};
use crate::conductor::job::{Job, JobQueue, Label, QueuePushError};
use crate::equity_redemption::{EquityRedemption, RedemptionAggregateId};
use crate::inventory::BroadcastingInventory;
use crate::inventory::view::{InFlightEquityLocation, InventoryView};
use crate::tokenized_equity_mint::{IssuerRequestId, TokenizedEquityMint};

/// Apalis queue type for [`WrappedEquityRecoveryJob`].
pub(crate) type WrappedEquityRecoveryJobQueue = JobQueue<WrappedEquityRecoveryJob>;

/// Dependencies the recovery job needs to claim the per-symbol concurrency
/// guard, read inventory, and send commands through the aggregate's store.
/// Services (raindex/wrapper/transfer) live on the store -- not here.
pub(crate) struct WrappedEquityRecoveryCtx {
    pub(crate) inventory: Arc<BroadcastingInventory>,
    pub(crate) store: Arc<Store<WrappedEquityRecovery>>,
    pub(crate) mint_store: Arc<Store<TokenizedEquityMint>>,
    pub(crate) redemption_store: Arc<Store<EquityRedemption>>,
    pub(crate) equity_in_progress: Arc<RwLock<HashSet<Symbol>>>,
    /// Queue used for delayed self-reschedule when the shared equity guard is
    /// held by another recovery/transfer job.
    pub(crate) queue: WrappedEquityRecoveryJobQueue,
    pub(crate) reschedule_interval: Duration,
}

/// Why a single recovery job attempt failed. Errors propagate up through
/// apalis; service-call failures inside the aggregate's command handlers
/// are recorded as `RecoveryFailed` events and don't surface here.
#[derive(Debug, Error)]
pub(crate) enum WrappedEquityRecoveryJobError {
    #[error("recovery aggregate error: {0}")]
    Aggregate(#[from] SendError<WrappedEquityRecovery>),

    #[error(transparent)]
    Domain(#[from] WrappedEquityRecoveryError),

    #[error(
        "inventory view reports both an active mint ({mint_id}) and active redemption \
         ({redemption_id}) for symbol {symbol} -- aborting recovery"
    )]
    ConflictingActiveTransfers {
        symbol: Symbol,
        mint_id: IssuerRequestId,
        redemption_id: RedemptionAggregateId,
    },

    #[error(
        "active mint {mint_id} for symbol {symbol} carries quantity {aggregate_shares}, \
         which does not match the wrapped-equity wallet snapshot {snapshot_shares} -- \
         refusing to dispatch to a stale aggregate"
    )]
    ActiveMintQuantityMismatch {
        symbol: Symbol,
        mint_id: IssuerRequestId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },

    #[error(
        "active redemption {redemption_id} for symbol {symbol} carries quantity \
         {aggregate_shares}, which does not match the wrapped-equity wallet snapshot \
         {snapshot_shares} -- refusing to dispatch to a stale aggregate"
    )]
    ActiveRedemptionQuantityMismatch {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },

    #[error("active mint {mint_id} for symbol {symbol} is missing from the mint store")]
    ActiveMintMissing {
        symbol: Symbol,
        mint_id: IssuerRequestId,
    },

    #[error(
        "active redemption {redemption_id} for symbol {symbol} is missing from the \
         redemption store"
    )]
    ActiveRedemptionMissing {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
    },

    #[error("active mint store error: {0}")]
    ActiveMintAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::tokenized_equity_mint::TokenizedEquityMint>,
        >,
    ),

    #[error("active redemption store error: {0}")]
    ActiveRedemptionAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::equity_redemption::EquityRedemption>,
        >,
    ),

    #[error("failed to reschedule recovery job after guard contention: {0}")]
    Reschedule(#[from] QueuePushError),
}

/// Apalis job payload. The reactor pushes one of these per symbol with a
/// positive `BaseWalletWrappedEquity` balance, generating a fresh
/// `recovery_id` at push time so apalis retries hit the same aggregate.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub(crate) struct WrappedEquityRecoveryJob {
    pub(crate) symbol: Symbol,
    pub(crate) recovery_id: WrappedEquityRecoveryId,
}

impl Job<WrappedEquityRecoveryCtx> for WrappedEquityRecoveryJob {
    type Output = ();
    type Error = WrappedEquityRecoveryJobError;

    const WORKER_NAME: &'static str = "wrapped-equity-recovery-worker";

    #[cfg(any(test, feature = "test-support"))]
    const JOB_KIND: crate::conductor::job::JobKind =
        crate::conductor::job::JobKind::WrappedEquityRecovery;

    fn label(&self) -> Label {
        Label::new(format!(
            "WrappedEquityRecovery:{}:{}",
            self.symbol, self.recovery_id
        ))
    }

    async fn perform(&self, ctx: &WrappedEquityRecoveryCtx) -> Result<Self::Output, Self::Error> {
        let symbol = self.symbol.clone();

        let Some(guard) = claim_guard(&ctx.equity_in_progress, &symbol) else {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Rescheduling wrapped equity recovery: equity_in_progress already held",
            );
            ctx.queue
                .clone()
                .push_with_delay(self.clone(), ctx.reschedule_interval)
                .await?;
            return Ok(());
        };

        if let Some(agg) = ctx.store.load(&self.recovery_id).await?
            && agg.is_terminal()
        {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Skipping wrapped equity recovery: aggregate already terminal",
            );
            drop(guard);
            return Ok(());
        }

        let Some(snapshot) = read_recovery_snapshot(&ctx.inventory, &symbol).await else {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Skipping wrapped equity recovery: no positive balance in inventory view",
            );
            drop(guard);
            return Ok(());
        };

        if let Err(error) = validate_active_aggregate_quantity(ctx, &symbol, &snapshot).await {
            warn!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                %error,
                "Wrapped equity recovery: active aggregate quantity mismatch; \
                 skipping dispatch",
            );
            drop(guard);
            return Err(error);
        }

        ctx.store
            .send(
                &self.recovery_id,
                WrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: snapshot.shares,
                },
            )
            .await?;

        info!(
            target: "rebalance",
            %symbol,
            recovery_id = %self.recovery_id,
            shares = %snapshot.shares,
            ?snapshot.dispatch,
            "Wrapped equity recovery: dispatched detection",
        );

        let result = match snapshot.dispatch {
            DispatchDecision::ActiveMint(mint_id) => ctx
                .store
                .send(
                    &self.recovery_id,
                    WrappedEquityRecoveryCommand::DispatchToMint { mint_id },
                )
                .await
                .map_err(Into::into),
            DispatchDecision::ActiveRedemption(redemption_id) => ctx
                .store
                .send(
                    &self.recovery_id,
                    WrappedEquityRecoveryCommand::DispatchToRedemption { redemption_id },
                )
                .await
                .map_err(Into::into),
            DispatchDecision::Orphan => {
                ctx.store
                    .send(
                        &self.recovery_id,
                        WrappedEquityRecoveryCommand::SubmitOrphanDeposit,
                    )
                    .await?;
                if let Some(agg) = ctx.store.load(&self.recovery_id).await?
                    && agg.is_terminal()
                {
                    Ok(())
                } else {
                    ctx.store
                        .send(
                            &self.recovery_id,
                            WrappedEquityRecoveryCommand::ConfirmOrphanDeposit,
                        )
                        .await
                        .map_err(Into::into)
                }
            }
            DispatchDecision::Conflict {
                mint_id,
                redemption_id,
            } => {
                let reason = format!(
                    "InventoryView reports active mint {mint_id} and active redemption \
                     {redemption_id} for symbol {symbol}; refusing to dispatch"
                );
                warn!(target: "rebalance", %symbol, %mint_id, %redemption_id, "Wrapped equity recovery: conflict");
                ctx.store
                    .send(
                        &self.recovery_id,
                        WrappedEquityRecoveryCommand::FailRecovery { reason },
                    )
                    .await?;
                Err(WrappedEquityRecoveryJobError::ConflictingActiveTransfers {
                    symbol: symbol.clone(),
                    mint_id,
                    redemption_id,
                })
            }
        };

        drop(guard);
        result
    }
}

struct RecoverySnapshot {
    shares: st0x_execution::FractionalShares,
    dispatch: DispatchDecision,
}

#[derive(Debug)]
enum DispatchDecision {
    ActiveMint(IssuerRequestId),
    ActiveRedemption(RedemptionAggregateId),
    Orphan,
    /// `InventoryView` reports both an active mint and an active redemption
    /// for the same symbol. A symbol can only be in one in-flight transfer
    /// at a time -- this is a corrupt-state signal, not a normal dispatch
    /// path.
    Conflict {
        mint_id: IssuerRequestId,
        redemption_id: RedemptionAggregateId,
    },
}

async fn read_recovery_snapshot(
    inventory: &BroadcastingInventory,
    symbol: &Symbol,
) -> Option<RecoverySnapshot> {
    let view = inventory.read().await;
    let shares = view.inflight_equity_at(symbol, InFlightEquityLocation::BaseWalletWrapped)?;
    if shares == st0x_execution::FractionalShares::ZERO {
        return None;
    }
    let dispatch = decide_dispatch(&view, symbol);
    drop(view);
    Some(RecoverySnapshot { shares, dispatch })
}

/// Confirms the active mint or redemption aggregate carries the same quantity
/// as the wrapped wallet snapshot. Without this check, the recovery stream
/// would record `snapshot.shares` for an aggregate that was actually set up
/// for a different amount, leaving the audit trail and the resumed work
/// disagreeing on how many shares moved.
async fn validate_active_aggregate_quantity(
    ctx: &WrappedEquityRecoveryCtx,
    symbol: &Symbol,
    snapshot: &RecoverySnapshot,
) -> Result<(), WrappedEquityRecoveryJobError> {
    match &snapshot.dispatch {
        DispatchDecision::ActiveMint(mint_id) => {
            let mint = ctx.mint_store.load(mint_id).await?.ok_or_else(|| {
                WrappedEquityRecoveryJobError::ActiveMintMissing {
                    symbol: symbol.clone(),
                    mint_id: mint_id.clone(),
                }
            })?;
            let aggregate_shares = FractionalShares::new(mint.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(WrappedEquityRecoveryJobError::ActiveMintQuantityMismatch {
                    symbol: symbol.clone(),
                    mint_id: mint_id.clone(),
                    snapshot_shares: snapshot.shares,
                    aggregate_shares,
                });
            }
            Ok(())
        }
        DispatchDecision::ActiveRedemption(redemption_id) => {
            let redemption = ctx
                .redemption_store
                .load(redemption_id)
                .await?
                .ok_or_else(|| WrappedEquityRecoveryJobError::ActiveRedemptionMissing {
                    symbol: symbol.clone(),
                    redemption_id: redemption_id.clone(),
                })?;
            let aggregate_shares = FractionalShares::new(redemption.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(
                    WrappedEquityRecoveryJobError::ActiveRedemptionQuantityMismatch {
                        symbol: symbol.clone(),
                        redemption_id: redemption_id.clone(),
                        snapshot_shares: snapshot.shares,
                        aggregate_shares,
                    },
                );
            }
            Ok(())
        }
        DispatchDecision::Orphan | DispatchDecision::Conflict { .. } => Ok(()),
    }
}

fn decide_dispatch(view: &InventoryView, symbol: &Symbol) -> DispatchDecision {
    match (view.active_mint(symbol), view.active_redemption(symbol)) {
        (Some(mint_id), Some(redemption_id)) => DispatchDecision::Conflict {
            mint_id: mint_id.clone(),
            redemption_id: redemption_id.clone(),
        },
        (Some(mint_id), None) => DispatchDecision::ActiveMint(mint_id.clone()),
        (None, Some(redemption_id)) => DispatchDecision::ActiveRedemption(redemption_id.clone()),
        (None, None) => DispatchDecision::Orphan,
    }
}

/// RAII helper that inserts `symbol` into `equity_in_progress` and removes
/// it on drop. Returns `None` if another task already holds the guard.
struct InProgressGuard {
    symbol: Symbol,
    set: Arc<RwLock<HashSet<Symbol>>>,
}

impl Drop for InProgressGuard {
    fn drop(&mut self) {
        let mut guard = match self.set.write() {
            Ok(guard) => guard,
            Err(poisoned) => {
                warn!(
                    symbol = %self.symbol,
                    "equity_in_progress lock poisoned during drop; releasing entry from inner guard"
                );
                poisoned.into_inner()
            }
        };
        guard.remove(&self.symbol);
    }
}

fn claim_guard(set: &Arc<RwLock<HashSet<Symbol>>>, symbol: &Symbol) -> Option<InProgressGuard> {
    let mut guard = match set.write() {
        Ok(guard) => guard,
        Err(poisoned) => {
            warn!(
                %symbol,
                "equity_in_progress lock poisoned; recovering inner guard so future recovery attempts can proceed"
            );
            poisoned.into_inner()
        }
    };
    if guard.contains(symbol) {
        return None;
    }
    guard.insert(symbol.clone());
    drop(guard);
    Some(InProgressGuard {
        symbol: symbol.clone(),
        set: Arc::clone(set),
    })
}

#[cfg(test)]
mod tests {
    use alloy::primitives::Address;
    use std::sync::{Arc, RwLock};
    use tokio::sync::broadcast;
    use uuid::Uuid;

    use st0x_event_sorcery::test_store;

    use super::super::aggregate::WrappedEquityRecoveryServices;
    use super::*;
    use crate::conductor::setup_apalis_tables;
    use crate::inventory::BroadcastingInventory;
    use crate::inventory::view::InventoryView;
    use crate::onchain::mock::MockRaindex;
    use crate::onchain::raindex::Raindex;
    use crate::rebalancing::equity::{CrossVenueEquityTransfer, EquityTransferServices};
    use crate::tokenization::mock::MockTokenizer;
    use crate::wrapper::Wrapper;
    use crate::wrapper::mock::MockWrapper;

    #[tokio::test]
    async fn guard_contention_reschedules_without_dropping_the_recovery() {
        let symbol = Symbol::new("AAPL").unwrap();
        let equity_in_progress = Arc::new(RwLock::new(HashSet::from([symbol.clone()])));

        let pool = sqlx::SqlitePool::connect(":memory:").await.unwrap();
        sqlx::migrate!().run(&pool).await.unwrap();
        setup_apalis_tables(&pool).await.unwrap();

        let raindex: Arc<dyn Raindex> = Arc::new(MockRaindex::new());
        let wrapper: Arc<dyn Wrapper> = Arc::new(MockWrapper::new());
        let transfer_services = EquityTransferServices {
            raindex: raindex.clone(),
            tokenizer: Arc::new(MockTokenizer::new()),
            wrapper: wrapper.clone(),
        };
        let mint_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let redemption_store = Arc::new(test_store(pool.clone(), transfer_services));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            raindex.clone(),
            Arc::new(MockTokenizer::new()),
            wrapper.clone(),
            Address::random(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        let store = Arc::new(test_store(
            pool.clone(),
            WrappedEquityRecoveryServices {
                raindex,
                wrapper,
                transfer,
            },
        ));

        let (sender, _receiver) = broadcast::channel(16);
        let inventory = Arc::new(BroadcastingInventory::new(InventoryView::default(), sender));
        let ctx = WrappedEquityRecoveryCtx {
            inventory,
            store,
            mint_store,
            redemption_store,
            equity_in_progress,
            queue: WrappedEquityRecoveryJobQueue::new(&pool),
            reschedule_interval: Duration::from_secs(1),
        };
        let job = WrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
        };

        job.perform(&ctx).await.unwrap();

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            state.is_none(),
            "guard-held perform() must not start recovery; aggregate should be absent, got {state:?}",
        );

        let (rescheduled,): (i64,) = sqlx::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
            .bind(std::any::type_name::<WrappedEquityRecoveryJob>())
            .fetch_one(ctx.queue.pool())
            .await
            .unwrap();
        assert_eq!(
            rescheduled, 1,
            "guard contention must reschedule the wrapped recovery job, not mark it done",
        );
    }

    #[tokio::test]
    async fn enqueue_dedup_matches_symbol_exactly_not_as_substring() {
        let pool = sqlx::SqlitePool::connect(":memory:").await.unwrap();
        setup_apalis_tables(&pool).await.unwrap();

        let mut queue = WrappedEquityRecoveryJobQueue::new(&pool);
        queue
            .push(WrappedEquityRecoveryJob {
                symbol: Symbol::new("GOOGL").unwrap(),
                recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
            })
            .await
            .unwrap();

        // The exact query the reactor uses to dedupe wrapped-recovery enqueues.
        const DEDUP_QUERY: &str = "SELECT COUNT(*) FROM Jobs \
             WHERE job_type = ? \
             AND status IN ('Pending', 'Queued', 'Running') \
             AND json_extract(job, '$.symbol') = ?";
        let job_type = std::any::type_name::<WrappedEquityRecoveryJob>();

        let (exact,): (i64,) = sqlx::query_as(DEDUP_QUERY)
            .bind(job_type)
            .bind("GOOGL")
            .fetch_one(&pool)
            .await
            .unwrap();
        assert_eq!(exact, 1, "exact symbol must match the queued GOOGL job");

        let (substring,): (i64,) = sqlx::query_as(DEDUP_QUERY)
            .bind(job_type)
            .bind("GOOG")
            .fetch_one(&pool)
            .await
            .unwrap();
        assert_eq!(
            substring, 0,
            "a substring ticker (GOOG) must not match the queued GOOGL job",
        );
    }
}
