//! Apalis job that orchestrates unwrapped-equity recovery.
//!
//! Enqueued per symbol with a positive `BaseWalletUnwrappedEquity`
//! balance. The job is a thin orchestrator: it reads `InventoryView`,
//! picks a dispatch path, and sends the command sequence through the
//! aggregate's store. All side effects (raindex deposit/confirm,
//! wrapper wrap/confirm, mint/redemption resume) live in the
//! aggregate's command handlers via its `Services`.
//!
//! Steps:
//!
//! 1. Claim the `equity_in_progress` guard for the symbol. If another
//!    task already holds it, the job returns a retryable error so apalis
//!    re-attempts until the guard frees. It must NOT skip silently: the
//!    job's per-symbol idempotency key blocks the next inventory poll from
//!    re-enqueuing, so a silent skip would strand the orphan.
//! 2. Read the inventory view's wallet balance + active mint/redemption
//!    maps to pick a `DispatchDecision`.
//! 3. Send `Detect` followed by the path-specific command sequence:
//!    `DispatchToMint`, `DispatchToRedemption`, or `SubmitOrphanWrap +
//!    ConfirmOrphanWrap + SubmitOrphanDeposit + ConfirmOrphanDeposit`.
//!    The aggregate's terminal state encodes the outcome; no separate
//!    completion command is needed.
//!
//! The job carries its `UnwrappedEquityRecoveryId` in the apalis
//! payload (generated by the reactor when pushing the job) so retries
//! target the same aggregate -- the next command in the sequence picks
//! up wherever the previous attempt stopped.

use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::sync::{Arc, RwLock};
use thiserror::Error;
use tracing::{debug, info, warn};

use st0x_event_sorcery::{SendError, Store};
use st0x_execution::{FractionalShares, Symbol};

use super::aggregate::{
    UnwrappedEquityRecovery, UnwrappedEquityRecoveryCommand, UnwrappedEquityRecoveryError,
    UnwrappedEquityRecoveryId,
};
use crate::conductor::job::{Job, JobQueue, Label};
use crate::equity_redemption::{EquityRedemption, RedemptionAggregateId};
use crate::inventory::BroadcastingInventory;
use crate::inventory::view::{InFlightEquityLocation, InventoryView};
use crate::tokenized_equity_mint::{IssuerRequestId, TokenizedEquityMint};

/// Apalis queue type for [`UnwrappedEquityRecoveryJob`].
pub(crate) type UnwrappedEquityRecoveryJobQueue = JobQueue<UnwrappedEquityRecoveryJob>;

/// Dependencies the recovery job needs to claim the per-symbol concurrency
/// guard, read inventory, and send commands through the aggregate's store.
/// Services (raindex/wrapper/transfer/wallet) live on the store -- not here.
pub(crate) struct UnwrappedEquityRecoveryCtx {
    pub(crate) inventory: Arc<BroadcastingInventory>,
    pub(crate) store: Arc<Store<UnwrappedEquityRecovery>>,
    pub(crate) mint_store: Arc<Store<TokenizedEquityMint>>,
    pub(crate) redemption_store: Arc<Store<EquityRedemption>>,
    pub(crate) equity_in_progress: Arc<RwLock<HashSet<Symbol>>>,
}

/// Why a single recovery job attempt failed. Errors propagate up through
/// apalis; service-call failures inside the aggregate's command handlers
/// are recorded as `RecoveryFailed` events and don't surface here.
#[derive(Debug, Error)]
pub(crate) enum UnwrappedEquityRecoveryJobError {
    #[error("recovery aggregate error: {0}")]
    Aggregate(#[from] SendError<UnwrappedEquityRecovery>),

    #[error(transparent)]
    Domain(#[from] UnwrappedEquityRecoveryError),

    #[error(
        "inventory view reports both an active mint ({mint_id}) and active redemption \
         ({redemption_id}) for symbol {symbol} -- aborting recovery"
    )]
    ConflictingActiveTransfers {
        symbol: Symbol,
        mint_id: IssuerRequestId,
        redemption_id: RedemptionAggregateId,
    },

    #[error(
        "active mint {mint_id} for symbol {symbol} carries quantity {aggregate_shares}, \
         which does not match the unwrapped-equity wallet snapshot {snapshot_shares} -- \
         refusing to dispatch to a stale aggregate"
    )]
    ActiveMintQuantityMismatch {
        symbol: Symbol,
        mint_id: IssuerRequestId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },

    #[error(
        "active redemption {redemption_id} for symbol {symbol} carries quantity \
         {aggregate_shares}, which does not match the unwrapped-equity wallet snapshot \
         {snapshot_shares} -- refusing to dispatch to a stale aggregate"
    )]
    ActiveRedemptionQuantityMismatch {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },

    #[error("active mint {mint_id} for symbol {symbol} is missing from the mint store")]
    ActiveMintMissing {
        symbol: Symbol,
        mint_id: IssuerRequestId,
    },

    #[error(
        "active redemption {redemption_id} for symbol {symbol} is missing from the \
         redemption store"
    )]
    ActiveRedemptionMissing {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
    },

    #[error("active mint store error: {0}")]
    ActiveMintAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::tokenized_equity_mint::TokenizedEquityMint>,
        >,
    ),

    #[error("active redemption store error: {0}")]
    ActiveRedemptionAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::equity_redemption::EquityRedemption>,
        >,
    ),
}

/// Apalis job payload. The reactor pushes one of these per symbol with a
/// positive `BaseWalletUnwrappedEquity` balance, generating a fresh
/// `recovery_id` at push time so apalis retries hit the same aggregate.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub(crate) struct UnwrappedEquityRecoveryJob {
    pub(crate) symbol: Symbol,
    pub(crate) recovery_id: UnwrappedEquityRecoveryId,
}

impl Job<UnwrappedEquityRecoveryCtx> for UnwrappedEquityRecoveryJob {
    type Output = ();
    type Error = UnwrappedEquityRecoveryJobError;

    const WORKER_NAME: &'static str = "unwrapped-equity-recovery-worker";

    #[cfg(any(test, feature = "test-support"))]
    const JOB_KIND: crate::conductor::job::JobKind =
        crate::conductor::job::JobKind::UnwrappedEquityRecovery;

    fn label(&self) -> Label {
        Label::new(format!(
            "UnwrappedEquityRecovery:{}:{}",
            self.symbol, self.recovery_id
        ))
    }

    async fn perform(&self, ctx: &UnwrappedEquityRecoveryCtx) -> Result<Self::Output, Self::Error> {
        let symbol = self.symbol.clone();

        let Some(guard) = claim_guard(&ctx.equity_in_progress, &symbol) else {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Skipping unwrapped equity recovery: equity_in_progress already held",
            );
            return Ok(());
        };

        let current_state = ctx.store.load(&self.recovery_id).await?;

        if let Some(state) = &current_state
            && state.is_terminal()
        {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Skipping unwrapped equity recovery: aggregate already terminal",
            );
            drop(guard);
            return Ok(());
        }

        let result = match current_state {
            None => start_from_detect(ctx, &self.recovery_id, &symbol).await,
            Some(UnwrappedEquityRecovery::Detected { .. }) => {
                resume_from_detected(ctx, &self.recovery_id, &symbol).await
            }
            Some(UnwrappedEquityRecovery::OrphanWrapSubmitted { .. }) => {
                resume_from_confirm_wrap(ctx, &self.recovery_id).await
            }
            Some(UnwrappedEquityRecovery::OrphanWrapped { .. }) => {
                resume_from_submit_deposit(ctx, &self.recovery_id).await
            }
            Some(UnwrappedEquityRecovery::OrphanDepositSubmitted { .. }) => {
                resume_from_confirm_deposit(ctx, &self.recovery_id).await
            }
            // Terminal states were filtered above; the aggregate's evolve
            // function never produces other non-terminal variants.
            Some(_) => Ok(()),
        };

        drop(guard);
        result
    }
}

/// Fresh recovery: read inventory, validate active-aggregate quantity, send
/// `Detect`, then dispatch from `Detected`.
async fn start_from_detect(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
    symbol: &Symbol,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    let Some(snapshot) = read_recovery_snapshot(&ctx.inventory, symbol).await else {
        debug!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            "Skipping unwrapped equity recovery: no positive balance in inventory view",
        );
        return Ok(());
    };

    if let Err(error) = validate_active_aggregate_quantity(ctx, symbol, &snapshot).await {
        warn!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            %error,
            "Unwrapped equity recovery: active aggregate quantity mismatch; skipping dispatch",
        );
        return Err(error);
    }

    ctx.store
        .send(
            recovery_id,
            UnwrappedEquityRecoveryCommand::Detect {
                symbol: symbol.clone(),
                shares: snapshot.shares,
            },
        )
        .await?;

    info!(
        target: "rebalance",
        %symbol,
        %recovery_id,
        shares = %snapshot.shares,
        ?snapshot.dispatch,
        "Unwrapped equity recovery: dispatched detection",
    );

    dispatch_from_detected(ctx, recovery_id, symbol, snapshot.dispatch).await
}

/// Resume from `Detected`: a previous attempt persisted `Detect` but crashed
/// before any dispatch command landed. Re-read inventory and dispatch.
async fn resume_from_detected(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
    symbol: &Symbol,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    let Some(snapshot) = read_recovery_snapshot(&ctx.inventory, symbol).await else {
        // Detected was persisted but the inventory no longer reports a positive
        // balance. The recovered tokens are either gone (recovered out-of-band)
        // or the previous snapshot was stale. Fail the aggregate so it leaves
        // the in-progress slot and a subsequent poll can start fresh.
        warn!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            "Resuming unwrapped recovery from Detected but inventory now reports zero balance; \
             failing the aggregate to free the symbol",
        );
        ctx.store
            .send(
                recovery_id,
                UnwrappedEquityRecoveryCommand::FailRecovery {
                    reason: "inventory reports zero unwrapped balance on resume from Detected"
                        .to_string(),
                },
            )
            .await?;
        return Ok(());
    };

    info!(
        target: "rebalance",
        %symbol,
        %recovery_id,
        ?snapshot.dispatch,
        "Resuming unwrapped recovery from Detected",
    );

    dispatch_from_detected(ctx, recovery_id, symbol, snapshot.dispatch).await
}

/// Picks the dispatch command from a `Detected` state. For the orphan path,
/// chains into the four-step sequence; for active mint/redemption, sends the
/// single dispatch command; for conflict, fails the aggregate and surfaces a
/// job-level error so the operator notices.
async fn dispatch_from_detected(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
    symbol: &Symbol,
    dispatch: DispatchDecision,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    match dispatch {
        DispatchDecision::ActiveMint(mint_id) => ctx
            .store
            .send(
                recovery_id,
                UnwrappedEquityRecoveryCommand::DispatchToMint { mint_id },
            )
            .await
            .map_err(Into::into),
        DispatchDecision::ActiveRedemption(redemption_id) => ctx
            .store
            .send(
                recovery_id,
                UnwrappedEquityRecoveryCommand::DispatchToRedemption { redemption_id },
            )
            .await
            .map_err(Into::into),
        DispatchDecision::Orphan => resume_from_submit_wrap(ctx, recovery_id).await,
        DispatchDecision::Conflict {
            mint_id,
            redemption_id,
        } => {
            let reason = format!(
                "InventoryView reports active mint {mint_id} and active redemption \
                 {redemption_id} for symbol {symbol}; refusing to dispatch"
            );
            warn!(target: "rebalance", %symbol, %mint_id, %redemption_id, "Unwrapped equity recovery: conflict");
            ctx.store
                .send(
                    recovery_id,
                    UnwrappedEquityRecoveryCommand::FailRecovery { reason },
                )
                .await?;
            Err(
                UnwrappedEquityRecoveryJobError::ConflictingActiveTransfers {
                    symbol: symbol.clone(),
                    mint_id,
                    redemption_id,
                },
            )
        }
    }
}

/// Starts the four-step orphan path. Each step is sent independently and
/// chains to the next via a `resume_from_*` function, so a retry that enters
/// at any orphan state can pick up at the right command instead of replaying
/// from `SubmitOrphanWrap`.
async fn resume_from_submit_wrap(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    ctx.store
        .send(
            recovery_id,
            UnwrappedEquityRecoveryCommand::SubmitOrphanWrap,
        )
        .await?;
    if aggregate_terminal(ctx, recovery_id).await? {
        return Ok(());
    }
    resume_from_confirm_wrap(ctx, recovery_id).await
}

/// Continues the orphan path from `OrphanWrapSubmitted` -- the wrap tx hash
/// is already persisted in state and the aggregate's command handler will
/// call `wrapper.confirm_wrap` on that tx.
async fn resume_from_confirm_wrap(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    ctx.store
        .send(
            recovery_id,
            UnwrappedEquityRecoveryCommand::ConfirmOrphanWrap,
        )
        .await?;
    if aggregate_terminal(ctx, recovery_id).await? {
        return Ok(());
    }
    resume_from_submit_deposit(ctx, recovery_id).await
}

/// Continues the orphan path from `OrphanWrapped` -- the wrapped amount is
/// persisted in state and the deposit command will use it.
async fn resume_from_submit_deposit(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    ctx.store
        .send(
            recovery_id,
            UnwrappedEquityRecoveryCommand::SubmitOrphanDeposit,
        )
        .await?;
    if aggregate_terminal(ctx, recovery_id).await? {
        return Ok(());
    }
    resume_from_confirm_deposit(ctx, recovery_id).await
}

/// Continues the orphan path from `OrphanDepositSubmitted` -- the deposit
/// tx hash is persisted in state and the aggregate confirms it via
/// `raindex.confirm_tx`.
async fn resume_from_confirm_deposit(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    ctx.store
        .send(
            recovery_id,
            UnwrappedEquityRecoveryCommand::ConfirmOrphanDeposit,
        )
        .await
        .map_err(Into::into)
}

async fn aggregate_terminal(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
) -> Result<bool, UnwrappedEquityRecoveryJobError> {
    Ok(ctx
        .store
        .load(recovery_id)
        .await?
        .is_some_and(|agg| agg.is_terminal()))
}

struct RecoverySnapshot {
    shares: FractionalShares,
    dispatch: DispatchDecision,
}

#[derive(Debug)]
enum DispatchDecision {
    ActiveMint(IssuerRequestId),
    ActiveRedemption(RedemptionAggregateId),
    Orphan,
    /// `InventoryView` reports both an active mint and an active redemption
    /// for the same symbol. A symbol can only be in one in-flight transfer
    /// at a time -- this is a corrupt-state signal, not a normal dispatch
    /// path.
    Conflict {
        mint_id: IssuerRequestId,
        redemption_id: RedemptionAggregateId,
    },
}

async fn read_recovery_snapshot(
    inventory: &BroadcastingInventory,
    symbol: &Symbol,
) -> Option<RecoverySnapshot> {
    let view = inventory.read().await;
    let shares = view.inflight_equity_at(symbol, InFlightEquityLocation::BaseWalletUnwrapped)?;
    if shares == FractionalShares::ZERO {
        return None;
    }
    let dispatch = decide_dispatch(&view, symbol);
    drop(view);
    Some(RecoverySnapshot { shares, dispatch })
}

/// Confirms the active mint or redemption aggregate carries the same quantity
/// as the unwrapped wallet snapshot. Without this check, the recovery stream
/// would record `snapshot.shares` for an aggregate that was actually set up
/// for a different amount, leaving the audit trail and the resumed work
/// disagreeing on how many shares moved.
async fn validate_active_aggregate_quantity(
    ctx: &UnwrappedEquityRecoveryCtx,
    symbol: &Symbol,
    snapshot: &RecoverySnapshot,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    match &snapshot.dispatch {
        DispatchDecision::ActiveMint(mint_id) => {
            let mint = ctx.mint_store.load(mint_id).await?.ok_or_else(|| {
                UnwrappedEquityRecoveryJobError::ActiveMintMissing {
                    symbol: symbol.clone(),
                    mint_id: mint_id.clone(),
                }
            })?;
            let aggregate_shares = FractionalShares::new(mint.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(
                    UnwrappedEquityRecoveryJobError::ActiveMintQuantityMismatch {
                        symbol: symbol.clone(),
                        mint_id: mint_id.clone(),
                        snapshot_shares: snapshot.shares,
                        aggregate_shares,
                    },
                );
            }
            Ok(())
        }
        DispatchDecision::ActiveRedemption(redemption_id) => {
            let redemption = ctx
                .redemption_store
                .load(redemption_id)
                .await?
                .ok_or_else(
                    || UnwrappedEquityRecoveryJobError::ActiveRedemptionMissing {
                        symbol: symbol.clone(),
                        redemption_id: redemption_id.clone(),
                    },
                )?;
            let aggregate_shares = FractionalShares::new(redemption.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(
                    UnwrappedEquityRecoveryJobError::ActiveRedemptionQuantityMismatch {
                        symbol: symbol.clone(),
                        redemption_id: redemption_id.clone(),
                        snapshot_shares: snapshot.shares,
                        aggregate_shares,
                    },
                );
            }
            Ok(())
        }
        DispatchDecision::Orphan | DispatchDecision::Conflict { .. } => Ok(()),
    }
}

fn decide_dispatch(view: &InventoryView, symbol: &Symbol) -> DispatchDecision {
    match (view.active_mint(symbol), view.active_redemption(symbol)) {
        (Some(mint_id), Some(redemption_id)) => DispatchDecision::Conflict {
            mint_id: mint_id.clone(),
            redemption_id: redemption_id.clone(),
        },
        (Some(mint_id), None) => DispatchDecision::ActiveMint(mint_id.clone()),
        (None, Some(redemption_id)) => DispatchDecision::ActiveRedemption(redemption_id.clone()),
        (None, None) => DispatchDecision::Orphan,
    }
}

/// RAII helper that inserts `symbol` into `equity_in_progress` and removes
/// it on drop. Returns `None` if another task already holds the guard.
struct InProgressGuard {
    symbol: Symbol,
    set: Arc<RwLock<HashSet<Symbol>>>,
}

impl Drop for InProgressGuard {
    fn drop(&mut self) {
        let mut guard = match self.set.write() {
            Ok(guard) => guard,
            Err(poisoned) => {
                warn!(
                    symbol = %self.symbol,
                    "equity_in_progress lock poisoned during drop; releasing entry from inner guard"
                );
                poisoned.into_inner()
            }
        };
        guard.remove(&self.symbol);
    }
}

fn claim_guard(set: &Arc<RwLock<HashSet<Symbol>>>, symbol: &Symbol) -> Option<InProgressGuard> {
    let mut guard = match set.write() {
        Ok(guard) => guard,
        Err(poisoned) => {
            warn!(
                %symbol,
                "equity_in_progress lock poisoned; recovering inner guard so future recovery attempts can proceed"
            );
            poisoned.into_inner()
        }
    };
    if guard.contains(symbol) {
        return None;
    }
    guard.insert(symbol.clone());
    drop(guard);
    Some(InProgressGuard {
        symbol: symbol.clone(),
        set: Arc::clone(set),
    })
}

#[cfg(test)]
mod tests {
    use alloy::primitives::Address;
    use tokio::sync::broadcast;
    use uuid::Uuid;

    use st0x_event_sorcery::test_store;

    use crate::onchain::mock::MockRaindex;
    use crate::onchain::raindex::Raindex;
    use crate::rebalancing::equity::{CrossVenueEquityTransfer, EquityTransferServices};
    use crate::tokenization::mock::MockTokenizer;
    use crate::wrapper::Wrapper;
    use crate::wrapper::mock::MockWrapper;

    use super::super::aggregate::UnwrappedEquityRecoveryServices;
    use super::*;

    /// Guard contention must surface as a retryable error, never a silent
    /// `Ok(())`. The job's per-symbol idempotency key blocks the next inventory
    /// poll from re-enqueuing, so a silent skip would strand the orphaned
    /// equity until apalis's finished-job cleanup eventually frees the key.
    /// Returning an error keeps the same job alive through apalis retries until
    /// the guard frees.
    #[tokio::test]
    async fn guard_contention_skips_without_halting_the_bot() {
        let symbol = Symbol::new("AAPL").unwrap();
        let equity_in_progress = Arc::new(RwLock::new(HashSet::from([symbol.clone()])));

        let pool = sqlx::SqlitePool::connect(":memory:").await.unwrap();
        sqlx::migrate!().run(&pool).await.unwrap();

        let raindex: Arc<dyn Raindex> = Arc::new(MockRaindex::new());
        let wrapper: Arc<dyn Wrapper> = Arc::new(MockWrapper::new());
        let transfer_services = EquityTransferServices {
            raindex: raindex.clone(),
            tokenizer: Arc::new(MockTokenizer::new()),
            wrapper: wrapper.clone(),
        };
        let mint_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let redemption_store = Arc::new(test_store(pool.clone(), transfer_services));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            raindex.clone(),
            Arc::new(MockTokenizer::new()),
            wrapper.clone(),
            Address::random(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        let store = Arc::new(test_store(
            pool,
            UnwrappedEquityRecoveryServices {
                raindex,
                wrapper,
                transfer,
                wallet: Address::random(),
            },
        ));

        let (sender, _receiver) = broadcast::channel(16);
        let inventory = Arc::new(BroadcastingInventory::new(InventoryView::default(), sender));

        let ctx = UnwrappedEquityRecoveryCtx {
            inventory,
            store,
            mint_store,
            redemption_store,
            equity_in_progress,
        };

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: UnwrappedEquityRecoveryId(Uuid::new_v4()),
        };

        // Guard contention must NOT yield a retryable error: exhausting the retry
        // budget on a held guard fires the shared apalis failure_notify and halts
        // the entire monitor. The job skips silently (matching the wrapped path)
        // and relies on the next inventory poll to re-dispatch once the guard frees.
        job.perform(&ctx).await.unwrap();

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            state.is_none(),
            "guard-held perform() must not start recovery; aggregate should be absent, got {state:?}",
        );
    }
}
