//! Dashboard DTO types for TypeScript codegen.
//!
//! This crate contains all types that derive `TS` for TypeScript type generation.
//! Keeping these in a separate crate allows the dashboard to build without waiting
//! for the full workspace. Domain types from `st0x-finance` are used for type
//! safety, with `#[ts(type = "string")]` overrides for TypeScript compatibility.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::path::Path;
use strum::VariantNames;
use ts_rs::TS;

use rain_math_float::Float;
use st0x_float_serde::float_string_serde;

use st0x_finance::{FractionalShares, Symbol};

mod inventory;
mod transfer;

pub use inventory::*;
pub use transfer::*;

/// Server-to-client WebSocket statements.
///
/// Each variant represents a domain-specific statement the server
/// pushes to connected clients. The `type` tag is serialized as
/// snake_case for the TypeScript client.
///
/// [`VariantNames`] derives `Statement::VARIANTS` — a compile-time
/// slice of all variant names in snake_case. Adding a variant
/// automatically updates the list; no manual bookkeeping needed.
/// The dashboard uses [`guard_ts`] output to validate incoming
/// WebSocket messages at runtime before dispatching.
#[derive(Debug, Clone, Serialize, VariantNames, TS)]
#[serde(tag = "type", content = "data", rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum Statement {
    CurrentState(Box<CurrentState>),
    TradeFill(Trade),
    PositionUpdate(Position),
    InventorySnapshot(Box<inventory::InventorySnapshot>),
    TransferUpdate(TransferOperation),
}

impl Statement {
    /// Generates a TypeScript module exporting `isStatement`, a runtime
    /// type guard for WebSocket message validation.
    ///
    /// `JSON.parse` returns `unknown`. The guard narrows it to
    /// `Statement` so the subsequent `matcher` call is type-safe —
    /// without it the dashboard would need an unsafe cast.
    ///
    /// Tags come from [`VARIANTS`] (derived by strum from this enum).
    /// The `satisfies StatementType[]` clause in the output gives a
    /// TypeScript-side compile error if the tags ever drift from the
    /// generated `Statement` type definition.
    ///
    /// The generated `isStatement` performs tag-only validation: it checks
    /// that the `type` field is a known `Statement` variant, but does not
    /// validate the shape of `data`. This is intentional — the TypeScript
    /// type system enforces payload shape after the type guard narrows to
    /// `Statement`, so per-variant structural checks would be redundant.
    /// Callers must not assume `data` is well-formed until they pattern-match
    /// on `type`.
    #[must_use]
    pub fn guard_ts() -> String {
        let tags = Self::VARIANTS
            .iter()
            .map(|tag| format!("  '{tag}'"))
            .collect::<Vec<_>>()
            .join(",\n");

        format!(
            r"// This file was generated by st0x-dto. Do not edit manually.
import type {{ Statement }} from './Statement'

type StatementType = Statement['type']

const STATEMENT_TYPES: Set<string> = new Set<StatementType>([
{tags}
] satisfies StatementType[])

export const isStatement = (value: unknown): value is Statement => {{
  if (typeof value !== 'object' || value === null) return false
  if (!('type' in value) || !('data' in value)) return false

  const record = value as Record<string, unknown>
  return typeof record['type'] === 'string' && STATEMENT_TYPES.has(record['type'])
}}
"
        )
    }
}

/// Dashboard snapshot sent to the frontend on connection.
#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CurrentState {
    pub trades: Vec<Trade>,
    pub inventory: Inventory,
    pub positions: Vec<Position>,
    pub settings: Settings,
    pub active_transfers: Vec<TransferOperation>,
    pub recent_transfers: Vec<TransferOperation>,
    pub warnings: Vec<TransferWarning>,
}

/// Operational settings shown on the dashboard overview.
#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Settings {
    pub equity_target: f64,
    pub equity_deviation: f64,
    pub usdc_target: Option<f64>,
    pub usdc_deviation: Option<f64>,
    pub execution_threshold: String,
    pub assets: Vec<AssetSettings>,
}

/// Per-asset operational settings.
#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct AssetSettings {
    #[ts(type = "string")]
    pub symbol: Symbol,
    pub trading: bool,
    pub rebalancing: bool,
    pub operational_limit: Option<String>,
}

/// Where a trade was executed.
#[derive(Debug, Clone, Copy, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum TradingVenue {
    Raindex,
    Alpaca,
    DryRun,
}

/// Whether the trade was a buy or sell.
#[derive(Debug, Clone, Copy, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum TradeDirection {
    Buy,
    Sell,
}

/// A completed trade fill.
#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Trade {
    /// Unique identifier for deduplication on reconnect.
    /// Onchain: `"tx_hash:log_index"`. Offchain: offchain order aggregate ID.
    pub id: String,
    pub filled_at: DateTime<Utc>,
    pub venue: TradingVenue,
    pub direction: TradeDirection,
    #[ts(type = "string")]
    pub symbol: Symbol,
    #[ts(type = "string")]
    pub shares: FractionalShares,
}

/// Per-symbol net position.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
pub struct Position {
    #[ts(type = "string")]
    pub symbol: Symbol,
    #[serde(with = "float_string_serde")]
    #[ts(type = "string")]
    pub net: Float,
}

/// Export all TypeScript bindings into `out_dir`.
///
/// Each type is written to `out_dir/TypeName.ts`. The caller controls
/// the output location explicitly -- no `TS_RS_EXPORT_DIR` magic.
///
/// # Errors
///
/// Returns [`ts_rs::ExportError`] if any type's binding file fails to
/// write (e.g., `out_dir` does not exist or is not writable).
pub fn export_bindings(out_dir: &Path) -> Result<(), ts_rs::ExportError> {
    Statement::export_all_to(out_dir)?;
    CurrentState::export_all_to(out_dir)?;
    Settings::export_all_to(out_dir)?;
    AssetSettings::export_all_to(out_dir)?;
    Trade::export_all_to(out_dir)?;
    Position::export_all_to(out_dir)?;
    SymbolInventory::export_all_to(out_dir)?;
    Inventory::export_all_to(out_dir)?;
    InventorySnapshot::export_all_to(out_dir)?;
    UsdcInventory::export_all_to(out_dir)?;
    TransferOperation::export_all_to(out_dir)?;
    EquityMintOperation::export_all_to(out_dir)?;
    EquityMintStatus::export_all_to(out_dir)?;
    EquityRedemptionOperation::export_all_to(out_dir)?;
    EquityRedemptionStatus::export_all_to(out_dir)?;
    UsdcBridgeDirection::export_all_to(out_dir)?;
    UsdcBridgeOperation::export_all_to(out_dir)?;
    UsdcBridgeStatus::export_all_to(out_dir)?;
    TransferWarning::export_all_to(out_dir)?;
    std::fs::write(out_dir.join("StatementGuard.ts"), Statement::guard_ts())
        .map_err(ts_rs::ExportError::Io)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use serde_json::json;
    use st0x_float_macro::float;

    use super::*;

    fn default_bindings_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../dashboard/src/lib/api")
    }

    #[test]
    fn statement_variants_matches_serde_wire_format() {
        assert_eq!(
            Statement::VARIANTS,
            &[
                "current_state",
                "trade_fill",
                "position_update",
                "inventory_snapshot",
                "transfer_update"
            ]
        );
    }

    #[test]
    fn statement_guard_contains_all_variants() {
        let guard = Statement::guard_ts();
        for tag in Statement::VARIANTS {
            assert!(
                guard.contains(tag),
                "guard should contain tag '{tag}', got:\n{guard}"
            );
        }
        assert!(guard.contains("isStatement"));
        assert!(guard.contains("import type { Statement }"));
    }

    #[test]
    fn statement_trade_fill_serializes_with_type_tag() {
        let trade = Trade {
            id: "0x0000000000000000000000000000000000000000000000000000000000000000:0".to_string(),
            filled_at: Utc::now(),
            venue: TradingVenue::Raindex,
            direction: TradeDirection::Buy,
            symbol: Symbol::new("AAPL").unwrap(),
            shares: FractionalShares::new(float!(10)),
        };
        let msg = Statement::TradeFill(trade);
        let json = serde_json::to_string(&msg).expect("serialization should succeed");
        assert!(
            json.contains(r#""type":"trade_fill""#),
            "expected trade_fill tag, got: {json}"
        );
        assert!(json.contains(r#""venue":"raindex""#));
        assert!(json.contains(r#""direction":"buy""#));
        assert!(json.contains(r#""symbol":"AAPL""#));
    }

    #[test]
    fn statement_current_state_serializes_with_type_tag() {
        let msg = Statement::CurrentState(Box::new(CurrentState {
            trades: Vec::new(),
            inventory: Inventory::empty(),
            positions: Vec::new(),
            settings: Settings {
                equity_target: 0.5,
                equity_deviation: 0.2,
                usdc_target: None,
                usdc_deviation: None,
                execution_threshold: "1 share".to_string(),
                assets: Vec::new(),
            },
            active_transfers: Vec::new(),
            recent_transfers: Vec::new(),
            warnings: Vec::new(),
        }));
        let json = serde_json::to_string(&msg).expect("serialization should succeed");
        assert!(json.contains(r#""type":"current_state""#));
        assert!(json.contains(r#""data":"#));
    }

    #[test]
    fn statement_position_update_serializes_with_type_tag() {
        let msg = Statement::PositionUpdate(Position {
            symbol: Symbol::new("AAPL").unwrap(),
            net: rain_math_float::Float::parse("5.5".to_string()).unwrap(),
        });
        let json = serde_json::to_value(&msg).expect("serialization should succeed");
        assert_eq!(json["type"], json!("position_update"));
        assert_eq!(json["data"]["symbol"], json!("AAPL"));
        assert_eq!(json["data"]["net"], json!("5.5"));
    }

    #[test]
    fn statement_inventory_snapshot_serializes_with_type_tag() {
        let msg = Statement::InventorySnapshot(Box::new(InventorySnapshot {
            inventory: Inventory::empty(),
            fetched_at: Utc::now(),
        }));
        let json = serde_json::to_string(&msg).expect("serialization should succeed");
        assert!(
            json.contains(r#""type":"inventory_snapshot""#),
            "expected inventory_snapshot tag, got: {json}"
        );
    }

    #[test]
    fn trade_serializes_all_fields() {
        let trade = Trade {
            id: "test-order-id".to_string(),
            filled_at: DateTime::from_timestamp(1_700_000_000, 0).unwrap(),
            venue: TradingVenue::Alpaca,
            direction: TradeDirection::Sell,
            symbol: Symbol::new("TSLA").unwrap(),
            shares: FractionalShares::new(float!(5.5)),
        };
        let json = serde_json::to_value(&trade).expect("serialization should succeed");
        assert_eq!(json["id"], json!("test-order-id"));
        assert_eq!(json["venue"], json!("alpaca"));
        assert_eq!(json["direction"], json!("sell"));
        assert_eq!(json["symbol"], json!("TSLA"));
        assert_eq!(json["shares"], json!("5.5"));
        assert!(json["filledAt"].is_string());
    }

    #[test]
    fn current_state_serializes_all_fields() {
        let state = CurrentState {
            trades: Vec::new(),
            inventory: Inventory::empty(),
            positions: Vec::new(),
            settings: Settings {
                equity_target: 0.5,
                equity_deviation: 0.2,
                usdc_target: None,
                usdc_deviation: None,
                execution_threshold: "$2".to_string(),
                assets: Vec::new(),
            },
            active_transfers: Vec::new(),
            recent_transfers: Vec::new(),
            warnings: Vec::new(),
        };
        let json = serde_json::to_value(&state).expect("serialization should succeed");
        assert_eq!(json["trades"], json!([]));
        assert_eq!(json["positions"], json!([]));
        assert_eq!(json["activeTransfers"], json!([]));
        assert_eq!(json["recentTransfers"], json!([]));
        assert_eq!(json["warnings"], json!([]));
        assert_eq!(json["settings"]["equityTarget"], json!(0.5));
        assert_eq!(json["settings"]["equityDeviation"], json!(0.2));
        assert_eq!(json["settings"]["usdcTarget"], json!(null));
        assert_eq!(json["settings"]["executionThreshold"], json!("$2"));
        assert!(json["inventory"].is_object());
    }

    #[derive(TS)]
    struct TestOnlyBinding {
        _canary: bool,
    }

    #[test]
    fn export_bindings_generates_files_in_dashboard_directory() {
        let out_dir = default_bindings_dir();

        export_bindings(&out_dir).unwrap();

        assert!(
            out_dir.join("Statement.ts").exists(),
            "Statement.ts should exist in {}/",
            out_dir.display()
        );
        assert!(
            out_dir.join("CurrentState.ts").exists(),
            "CurrentState.ts should exist in {}/",
            out_dir.display()
        );
        assert!(
            out_dir.join("StatementGuard.ts").exists(),
            "StatementGuard.ts should exist in {}/",
            out_dir.display()
        );

        TestOnlyBinding::export_all_to(&out_dir).unwrap();
        let test_file = out_dir.join("TestOnlyBinding.ts");
        let contents = std::fs::read_to_string(&test_file).unwrap_or_else(|error| {
            panic!(
                "test-only binding should be readable at {}: {error}",
                test_file.display()
            )
        });
        assert!(
            contents.contains("TestOnlyBinding"),
            "generated file should contain the type name, got: {contents}"
        );
        assert!(
            contents.contains("_canary"),
            "generated file should contain the field name, got: {contents}"
        );
        std::fs::remove_file(&test_file).unwrap();
    }
}
